// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: coordinator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CellCoordinator_FetchConfig_FullMethodName        = "/dev.wiggle.proto.CellCoordinator/FetchConfig"
	CellCoordinator_Register_FullMethodName           = "/dev.wiggle.proto.CellCoordinator/Register"
	CellCoordinator_Heartbeat_FullMethodName          = "/dev.wiggle.proto.CellCoordinator/Heartbeat"
	CellCoordinator_Deregister_FullMethodName         = "/dev.wiggle.proto.CellCoordinator/Deregister"
	CellCoordinator_Resolve_FullMethodName            = "/dev.wiggle.proto.CellCoordinator/Resolve"
	CellCoordinator_ActiveCells_FullMethodName        = "/dev.wiggle.proto.CellCoordinator/ActiveCells"
	CellCoordinator_OpenEpoch_FullMethodName          = "/dev.wiggle.proto.CellCoordinator/OpenEpoch"
	CellCoordinator_SetRing_FullMethodName            = "/dev.wiggle.proto.CellCoordinator/SetRing"
	CellCoordinator_RegisterWorkflow_FullMethodName   = "/dev.wiggle.proto.CellCoordinator/RegisterWorkflow"
	CellCoordinator_DeregisterWorkflow_FullMethodName = "/dev.wiggle.proto.CellCoordinator/DeregisterWorkflow"
	CellCoordinator_ListWorkflows_FullMethodName      = "/dev.wiggle.proto.CellCoordinator/ListWorkflows"
)

// CellCoordinatorClient is the client API for CellCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The optional cell coordinator's control plane. It shards a workflow's instances across isolated
// cells; it is never on the data path (poll/complete go straight to a cell). See
// docs/cell-coordinator-tickets.md and the design reference for the full model.
type CellCoordinatorClient interface {
	// ---- node lifecycle (a server node <-> coordinator) ----
	FetchConfig(ctx context.Context, in *FetchConfigRequest, opts ...grpc.CallOption) (*NodeConfig, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *CoordinatorHeartbeatRequest, opts ...grpc.CallOption) (*CoordinatorHeartbeatResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*Empty, error)
	// ---- resolution (clients & workers; cached, region-aware) ----
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	ActiveCells(ctx context.Context, in *ActiveCellsRequest, opts ...grpc.CallOption) (*ActiveCellsResponse, error)
	// ---- admin (reconfiguration & definition fan-out) ----
	OpenEpoch(ctx context.Context, in *OpenEpochRequest, opts ...grpc.CallOption) (*Policy, error)
	SetRing(ctx context.Context, in *SetRingRequest, opts ...grpc.CallOption) (*Policy, error)
	RegisterWorkflow(ctx context.Context, in *RegisterWorkflowRequest, opts ...grpc.CallOption) (*RegisterWorkflowResponse, error)
	DeregisterWorkflow(ctx context.Context, in *DeregisterWorkflowRequest, opts ...grpc.CallOption) (*DeregisterWorkflowResponse, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
}

type cellCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCellCoordinatorClient(cc grpc.ClientConnInterface) CellCoordinatorClient {
	return &cellCoordinatorClient{cc}
}

func (c *cellCoordinatorClient) FetchConfig(ctx context.Context, in *FetchConfigRequest, opts ...grpc.CallOption) (*NodeConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeConfig)
	err := c.cc.Invoke(ctx, CellCoordinator_FetchConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, CellCoordinator_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) Heartbeat(ctx context.Context, in *CoordinatorHeartbeatRequest, opts ...grpc.CallOption) (*CoordinatorHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorHeartbeatResponse)
	err := c.cc.Invoke(ctx, CellCoordinator_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CellCoordinator_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, CellCoordinator_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) ActiveCells(ctx context.Context, in *ActiveCellsRequest, opts ...grpc.CallOption) (*ActiveCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActiveCellsResponse)
	err := c.cc.Invoke(ctx, CellCoordinator_ActiveCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) OpenEpoch(ctx context.Context, in *OpenEpochRequest, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, CellCoordinator_OpenEpoch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) SetRing(ctx context.Context, in *SetRingRequest, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, CellCoordinator_SetRing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) RegisterWorkflow(ctx context.Context, in *RegisterWorkflowRequest, opts ...grpc.CallOption) (*RegisterWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkflowResponse)
	err := c.cc.Invoke(ctx, CellCoordinator_RegisterWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) DeregisterWorkflow(ctx context.Context, in *DeregisterWorkflowRequest, opts ...grpc.CallOption) (*DeregisterWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterWorkflowResponse)
	err := c.cc.Invoke(ctx, CellCoordinator_DeregisterWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellCoordinatorClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, CellCoordinator_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CellCoordinatorServer is the server API for CellCoordinator service.
// All implementations must embed UnimplementedCellCoordinatorServer
// for forward compatibility.
//
// The optional cell coordinator's control plane. It shards a workflow's instances across isolated
// cells; it is never on the data path (poll/complete go straight to a cell). See
// docs/cell-coordinator-tickets.md and the design reference for the full model.
type CellCoordinatorServer interface {
	// ---- node lifecycle (a server node <-> coordinator) ----
	FetchConfig(context.Context, *FetchConfigRequest) (*NodeConfig, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *CoordinatorHeartbeatRequest) (*CoordinatorHeartbeatResponse, error)
	Deregister(context.Context, *DeregisterRequest) (*Empty, error)
	// ---- resolution (clients & workers; cached, region-aware) ----
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	ActiveCells(context.Context, *ActiveCellsRequest) (*ActiveCellsResponse, error)
	// ---- admin (reconfiguration & definition fan-out) ----
	OpenEpoch(context.Context, *OpenEpochRequest) (*Policy, error)
	SetRing(context.Context, *SetRingRequest) (*Policy, error)
	RegisterWorkflow(context.Context, *RegisterWorkflowRequest) (*RegisterWorkflowResponse, error)
	DeregisterWorkflow(context.Context, *DeregisterWorkflowRequest) (*DeregisterWorkflowResponse, error)
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	mustEmbedUnimplementedCellCoordinatorServer()
}

// UnimplementedCellCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCellCoordinatorServer struct{}

func (UnimplementedCellCoordinatorServer) FetchConfig(context.Context, *FetchConfigRequest) (*NodeConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchConfig not implemented")
}
func (UnimplementedCellCoordinatorServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCellCoordinatorServer) Heartbeat(context.Context, *CoordinatorHeartbeatRequest) (*CoordinatorHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCellCoordinatorServer) Deregister(context.Context, *DeregisterRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedCellCoordinatorServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedCellCoordinatorServer) ActiveCells(context.Context, *ActiveCellsRequest) (*ActiveCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActiveCells not implemented")
}
func (UnimplementedCellCoordinatorServer) OpenEpoch(context.Context, *OpenEpochRequest) (*Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenEpoch not implemented")
}
func (UnimplementedCellCoordinatorServer) SetRing(context.Context, *SetRingRequest) (*Policy, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRing not implemented")
}
func (UnimplementedCellCoordinatorServer) RegisterWorkflow(context.Context, *RegisterWorkflowRequest) (*RegisterWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorkflow not implemented")
}
func (UnimplementedCellCoordinatorServer) DeregisterWorkflow(context.Context, *DeregisterWorkflowRequest) (*DeregisterWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterWorkflow not implemented")
}
func (UnimplementedCellCoordinatorServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedCellCoordinatorServer) mustEmbedUnimplementedCellCoordinatorServer() {}
func (UnimplementedCellCoordinatorServer) testEmbeddedByValue()                         {}

// UnsafeCellCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CellCoordinatorServer will
// result in compilation errors.
type UnsafeCellCoordinatorServer interface {
	mustEmbedUnimplementedCellCoordinatorServer()
}

func RegisterCellCoordinatorServer(s grpc.ServiceRegistrar, srv CellCoordinatorServer) {
	// If the following call panics, it indicates UnimplementedCellCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CellCoordinator_ServiceDesc, srv)
}

func _CellCoordinator_FetchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).FetchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_FetchConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).FetchConfig(ctx, req.(*FetchConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).Heartbeat(ctx, req.(*CoordinatorHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_ActiveCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).ActiveCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_ActiveCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).ActiveCells(ctx, req.(*ActiveCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_OpenEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).OpenEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_OpenEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).OpenEpoch(ctx, req.(*OpenEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_SetRing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).SetRing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_SetRing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).SetRing(ctx, req.(*SetRingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_RegisterWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).RegisterWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_RegisterWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).RegisterWorkflow(ctx, req.(*RegisterWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_DeregisterWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).DeregisterWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_DeregisterWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).DeregisterWorkflow(ctx, req.(*DeregisterWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellCoordinator_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellCoordinatorServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellCoordinator_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellCoordinatorServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CellCoordinator_ServiceDesc is the grpc.ServiceDesc for CellCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CellCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dev.wiggle.proto.CellCoordinator",
	HandlerType: (*CellCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchConfig",
			Handler:    _CellCoordinator_FetchConfig_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _CellCoordinator_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CellCoordinator_Heartbeat_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _CellCoordinator_Deregister_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _CellCoordinator_Resolve_Handler,
		},
		{
			MethodName: "ActiveCells",
			Handler:    _CellCoordinator_ActiveCells_Handler,
		},
		{
			MethodName: "OpenEpoch",
			Handler:    _CellCoordinator_OpenEpoch_Handler,
		},
		{
			MethodName: "SetRing",
			Handler:    _CellCoordinator_SetRing_Handler,
		},
		{
			MethodName: "RegisterWorkflow",
			Handler:    _CellCoordinator_RegisterWorkflow_Handler,
		},
		{
			MethodName: "DeregisterWorkflow",
			Handler:    _CellCoordinator_DeregisterWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _CellCoordinator_ListWorkflows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator.proto",
}
