// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: coordinator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EpochStatus int32

const (
	EpochStatus_EPOCH_STATUS_UNSPECIFIED EpochStatus = 0
	EpochStatus_OPEN                     EpochStatus = 1
	EpochStatus_DRAINING                 EpochStatus = 2
	EpochStatus_RETIRED                  EpochStatus = 3
)

// Enum value maps for EpochStatus.
var (
	EpochStatus_name = map[int32]string{
		0: "EPOCH_STATUS_UNSPECIFIED",
		1: "OPEN",
		2: "DRAINING",
		3: "RETIRED",
	}
	EpochStatus_value = map[string]int32{
		"EPOCH_STATUS_UNSPECIFIED": 0,
		"OPEN":                     1,
		"DRAINING":                 2,
		"RETIRED":                  3,
	}
)

func (x EpochStatus) Enum() *EpochStatus {
	p := new(EpochStatus)
	*p = x
	return p
}

func (x EpochStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EpochStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_proto_enumTypes[0].Descriptor()
}

func (EpochStatus) Type() protoreflect.EnumType {
	return &file_coordinator_proto_enumTypes[0]
}

func (x EpochStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EpochStatus.Descriptor instead.
func (EpochStatus) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

type Directive int32

const (
	Directive_DIRECTIVE_UNSPECIFIED Directive = 0
	Directive_RECONFIGURE           Directive = 1
	Directive_DRAIN                 Directive = 2
)

// Enum value maps for Directive.
var (
	Directive_name = map[int32]string{
		0: "DIRECTIVE_UNSPECIFIED",
		1: "RECONFIGURE",
		2: "DRAIN",
	}
	Directive_value = map[string]int32{
		"DIRECTIVE_UNSPECIFIED": 0,
		"RECONFIGURE":           1,
		"DRAIN":                 2,
	}
)

func (x Directive) Enum() *Directive {
	p := new(Directive)
	*p = x
	return p
}

func (x Directive) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Directive) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_proto_enumTypes[1].Descriptor()
}

func (Directive) Type() protoreflect.EnumType {
	return &file_coordinator_proto_enumTypes[1]
}

func (x Directive) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Directive.Descriptor instead.
func (Directive) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

type Tls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	CaRef         string                 `protobuf:"bytes,2,opt,name=ca_ref,json=caRef,proto3" json:"ca_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tls) Reset() {
	*x = Tls{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tls) ProtoMessage() {}

func (x *Tls) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tls.ProtoReflect.Descriptor instead.
func (*Tls) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *Tls) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Tls) GetCaRef() string {
	if x != nil {
		return x.CaRef
	}
	return ""
}

// What Resolve / ActiveCells hand back: a gRPC target + TLS, not a bare host:port.
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // e.g. "grpcs://acme-e7.us-east.cells.example.net:8443"
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"` // where this cell's data lives
	Tls           *Tls                   `protobuf:"bytes,3,opt,name=tls,proto3" json:"tls,omitempty"`
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"` // optional explicit node list for client-side LB
	TtlSeconds    uint32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *Endpoint) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Endpoint) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Endpoint) GetTls() *Tls {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Endpoint) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Endpoint) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// A node's storage config (maps to ServerConfig's jdbc* fields).
type StorageSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	JdbcUrl       string                 `protobuf:"bytes,2,opt,name=jdbc_url,json=jdbcUrl,proto3" json:"jdbc_url,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	SecretRef     string                 `protobuf:"bytes,4,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"` // resolved by the node, never stored by the coordinator
	PoolSize      uint32                 `protobuf:"varint,5,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageSpec) Reset() {
	*x = StorageSpec{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSpec) ProtoMessage() {}

func (x *StorageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageSpec.ProtoReflect.Descriptor instead.
func (*StorageSpec) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *StorageSpec) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *StorageSpec) GetJdbcUrl() string {
	if x != nil {
		return x.JdbcUrl
	}
	return ""
}

func (x *StorageSpec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StorageSpec) GetSecretRef() string {
	if x != nil {
		return x.SecretRef
	}
	return ""
}

func (x *StorageSpec) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

// A sparse tuning overlay: an unset field means "keep the node's default".
type Tuning struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PollIntervalMillis *uint32                `protobuf:"varint,1,opt,name=poll_interval_millis,json=pollIntervalMillis,proto3,oneof" json:"poll_interval_millis,omitempty"`
	LeaseMillis        *uint32                `protobuf:"varint,2,opt,name=lease_millis,json=leaseMillis,proto3,oneof" json:"lease_millis,omitempty"`
	LongPollMaxMillis  *uint32                `protobuf:"varint,3,opt,name=long_poll_max_millis,json=longPollMaxMillis,proto3,oneof" json:"long_poll_max_millis,omitempty"`
	RetentionMillis    *uint64                `protobuf:"varint,4,opt,name=retention_millis,json=retentionMillis,proto3,oneof" json:"retention_millis,omitempty"`
	Memory             *Tuning_Memory         `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Tuning) Reset() {
	*x = Tuning{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuning) ProtoMessage() {}

func (x *Tuning) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuning.ProtoReflect.Descriptor instead.
func (*Tuning) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *Tuning) GetPollIntervalMillis() uint32 {
	if x != nil && x.PollIntervalMillis != nil {
		return *x.PollIntervalMillis
	}
	return 0
}

func (x *Tuning) GetLeaseMillis() uint32 {
	if x != nil && x.LeaseMillis != nil {
		return *x.LeaseMillis
	}
	return 0
}

func (x *Tuning) GetLongPollMaxMillis() uint32 {
	if x != nil && x.LongPollMaxMillis != nil {
		return *x.LongPollMaxMillis
	}
	return 0
}

func (x *Tuning) GetRetentionMillis() uint64 {
	if x != nil && x.RetentionMillis != nil {
		return *x.RetentionMillis
	}
	return 0
}

func (x *Tuning) GetMemory() *Tuning_Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

// One slot of a placement ring: shard -> cell, region-tagged (R24).
type RingSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RingSlot) Reset() {
	*x = RingSlot{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingSlot) ProtoMessage() {}

func (x *RingSlot) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingSlot.ProtoReflect.Descriptor instead.
func (*RingSlot) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *RingSlot) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *RingSlot) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *RingSlot) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type EpochRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ring          []*RingSlot            `protobuf:"bytes,1,rep,name=ring,proto3" json:"ring,omitempty"`
	Status        EpochStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=dev.wiggle.proto.EpochStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochRing) Reset() {
	*x = EpochRing{}
	mi := &file_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochRing) ProtoMessage() {}

func (x *EpochRing) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochRing.ProtoReflect.Descriptor instead.
func (*EpochRing) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *EpochRing) GetRing() []*RingSlot {
	if x != nil {
		return x.Ring
	}
	return nil
}

func (x *EpochRing) GetStatus() EpochStatus {
	if x != nil {
		return x.Status
	}
	return EpochStatus_EPOCH_STATUS_UNSPECIFIED
}

// The coordinator's per-namespace policy -- O(namespaces x epochs x cells), never per-instance.
type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CurrentEpoch  uint64                 `protobuf:"varint,2,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	Epochs        map[uint64]*EpochRing  `protobuf:"bytes,3,rep,name=epochs,proto3" json:"epochs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Revision      uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"` // CAS token for reconfiguration writes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *Policy) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Policy) GetCurrentEpoch() uint64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *Policy) GetEpochs() map[uint64]*EpochRing {
	if x != nil {
		return x.Epochs
	}
	return nil
}

func (x *Policy) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EngineVersion string                 `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	AdvertiseHost string                 `protobuf:"bytes,3,opt,name=advertise_host,json=advertiseHost,proto3" json:"advertise_host,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	CellId        string                 `protobuf:"bytes,5,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"` // the cell this node was provisioned into; "" -> the namespace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *NodeInfo) GetAdvertiseHost() string {
	if x != nil {
		return x.AdvertiseHost
	}
	return ""
}

func (x *NodeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeInfo) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type FetchConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Node          *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchConfigRequest) Reset() {
	*x = FetchConfigRequest{}
	mi := &file_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigRequest) ProtoMessage() {}

func (x *FetchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigRequest.ProtoReflect.Descriptor instead.
func (*FetchConfigRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *FetchConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FetchConfigRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type Expected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngineVersion string                 `protobuf:"bytes,1,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	SchemaVersion uint32                 `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expected) Reset() {
	*x = Expected{}
	mi := &file_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expected) ProtoMessage() {}

func (x *Expected) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expected.ProtoReflect.Descriptor instead.
func (*Expected) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *Expected) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *Expected) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"` // newer than the node's => re-fetch (push-free)
	Expected      *Expected              `protobuf:"bytes,3,opt,name=expected,proto3" json:"expected,omitempty"`      // version / schema guardrail
	Storage       *StorageSpec           `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	Tuning        *Tuning                `protobuf:"bytes,5,opt,name=tuning,proto3" json:"tuning,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Epoch         uint64                 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`          // the epoch this node mints new instances into
	Shards        []uint32               `protobuf:"varint,8,rep,packed,name=shards,proto3" json:"shards,omitempty"` // the shards this node's cell owns in that epoch (ids are stamped with one of these)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *NodeConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NodeConfig) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *NodeConfig) GetExpected() *Expected {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *NodeConfig) GetStorage() *StorageSpec {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *NodeConfig) GetTuning() *Tuning {
	if x != nil {
		return x.Tuning
	}
	return nil
}

func (x *NodeConfig) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *NodeConfig) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *NodeConfig) GetShards() []uint32 {
	if x != nil {
		return x.Shards
	}
	return nil
}

type RegisteredNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	EngineVersion string                 `protobuf:"bytes,3,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // epoch millis
	CellId        string                 `protobuf:"bytes,6,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`           // the cell this node belongs to (nodes sharing a DB); "" -> the namespace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredNode) Reset() {
	*x = RegisteredNode{}
	mi := &file_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredNode) ProtoMessage() {}

func (x *RegisteredNode) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredNode.ProtoReflect.Descriptor instead.
func (*RegisteredNode) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *RegisteredNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisteredNode) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisteredNode) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *RegisteredNode) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisteredNode) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *RegisteredNode) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Node             *RegisteredNode        `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	ConfigGeneration uint64                 `protobuf:"varint,3,opt,name=config_generation,json=configGeneration,proto3" json:"config_generation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterRequest) GetNode() *RegisteredNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RegisterRequest) GetConfigGeneration() uint64 {
	if x != nil {
		return x.ConfigGeneration
	}
	return 0
}

type RegisterResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	NodeId                   string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	Directives               []Directive            `protobuf:"varint,3,rep,packed,name=directives,proto3,enum=dev.wiggle.proto.Directive" json:"directives,omitempty"`
	Epoch                    uint64                 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`          // initial placement: the epoch this node mints into
	Shards                   []uint32               `protobuf:"varint,5,rep,packed,name=shards,proto3" json:"shards,omitempty"` // initial placement: the shards this node's cell owns
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetDirectives() []Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *RegisterResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RegisterResponse) GetShards() []uint32 {
	if x != nil {
		return x.Shards
	}
	return nil
}

type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InFlight      uint32                 `protobuf:"varint,1,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	Leader        bool                   `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	LiveByEpoch   map[uint64]uint32      `protobuf:"bytes,3,rep,name=live_by_epoch,json=liveByEpoch,proto3" json:"live_by_epoch,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // epoch -> live instance count; drives cell retire (R21)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_coordinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{14}
}

func (x *Health) GetInFlight() uint32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *Health) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *Health) GetLiveByEpoch() map[uint64]uint32 {
	if x != nil {
		return x.LiveByEpoch
	}
	return nil
}

type CoordinatorHeartbeatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConfigGeneration uint64                 `protobuf:"varint,2,opt,name=config_generation,json=configGeneration,proto3" json:"config_generation,omitempty"`
	Health           *Health                `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CoordinatorHeartbeatRequest) Reset() {
	*x = CoordinatorHeartbeatRequest{}
	mi := &file_coordinator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorHeartbeatRequest) ProtoMessage() {}

func (x *CoordinatorHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{15}
}

func (x *CoordinatorHeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CoordinatorHeartbeatRequest) GetConfigGeneration() uint64 {
	if x != nil {
		return x.ConfigGeneration
	}
	return 0
}

func (x *CoordinatorHeartbeatRequest) GetHealth() *Health {
	if x != nil {
		return x.Health
	}
	return nil
}

type CoordinatorHeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ConfigGeneration uint64                 `protobuf:"varint,2,opt,name=config_generation,json=configGeneration,proto3" json:"config_generation,omitempty"` // newer => node re-fetches
	Directives       []Directive            `protobuf:"varint,3,rep,packed,name=directives,proto3,enum=dev.wiggle.proto.Directive" json:"directives,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CoordinatorHeartbeatResponse) Reset() {
	*x = CoordinatorHeartbeatResponse{}
	mi := &file_coordinator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorHeartbeatResponse) ProtoMessage() {}

func (x *CoordinatorHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{16}
}

func (x *CoordinatorHeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CoordinatorHeartbeatResponse) GetConfigGeneration() uint64 {
	if x != nil {
		return x.ConfigGeneration
	}
	return 0
}

func (x *CoordinatorHeartbeatResponse) GetDirectives() []Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_coordinator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{17}
}

func (x *DeregisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ResolveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to By:
	//
	//	*ResolveRequest_InstanceId
	//	*ResolveRequest_Namespace
	By            isResolveRequest_By `protobuf_oneof:"by"`
	CallerRegion  string              `protobuf:"bytes,3,opt,name=caller_region,json=callerRegion,proto3" json:"caller_region,omitempty"` // region-appropriate address, never a different cell (R24)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_coordinator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{18}
}

func (x *ResolveRequest) GetBy() isResolveRequest_By {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *ResolveRequest) GetInstanceId() string {
	if x != nil {
		if x, ok := x.By.(*ResolveRequest_InstanceId); ok {
			return x.InstanceId
		}
	}
	return ""
}

func (x *ResolveRequest) GetNamespace() string {
	if x != nil {
		if x, ok := x.By.(*ResolveRequest_Namespace); ok {
			return x.Namespace
		}
	}
	return ""
}

func (x *ResolveRequest) GetCallerRegion() string {
	if x != nil {
		return x.CallerRegion
	}
	return ""
}

type isResolveRequest_By interface {
	isResolveRequest_By()
}

type ResolveRequest_InstanceId struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3,oneof"` // route a specific instance (parsed ns.epoch.shard)
}

type ResolveRequest_Namespace struct {
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3,oneof"` // resolve the CURRENT epoch for a new start
}

func (*ResolveRequest_InstanceId) isResolveRequest_By() {}

func (*ResolveRequest_Namespace) isResolveRequest_By() {}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_coordinator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{19}
}

func (x *ResolveResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResolveResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ResolveResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ResolveResponse) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ActiveCellsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CallerRegion  string                 `protobuf:"bytes,2,opt,name=caller_region,json=callerRegion,proto3" json:"caller_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveCellsRequest) Reset() {
	*x = ActiveCellsRequest{}
	mi := &file_coordinator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCellsRequest) ProtoMessage() {}

func (x *ActiveCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCellsRequest.ProtoReflect.Descriptor instead.
func (*ActiveCellsRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{20}
}

func (x *ActiveCellsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ActiveCellsRequest) GetCallerRegion() string {
	if x != nil {
		return x.CallerRegion
	}
	return ""
}

type ActiveCellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"` // bump => re-fetch (worker reconciles its poll set)
	Cells         []*Endpoint            `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`            // region-local cells with live work
	TtlSeconds    uint32                 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveCellsResponse) Reset() {
	*x = ActiveCellsResponse{}
	mi := &file_coordinator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCellsResponse) ProtoMessage() {}

func (x *ActiveCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCellsResponse.ProtoReflect.Descriptor instead.
func (*ActiveCellsResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{21}
}

func (x *ActiveCellsResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ActiveCellsResponse) GetCells() []*Endpoint {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *ActiveCellsResponse) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type OpenEpochRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Ring          []*RingSlot            `protobuf:"bytes,2,rep,name=ring,proto3" json:"ring,omitempty"` // scale out -> gen++
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenEpochRequest) Reset() {
	*x = OpenEpochRequest{}
	mi := &file_coordinator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenEpochRequest) ProtoMessage() {}

func (x *OpenEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenEpochRequest.ProtoReflect.Descriptor instead.
func (*OpenEpochRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{22}
}

func (x *OpenEpochRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OpenEpochRequest) GetRing() []*RingSlot {
	if x != nil {
		return x.Ring
	}
	return nil
}

type SetRingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Ring          []*RingSlot            `protobuf:"bytes,3,rep,name=ring,proto3" json:"ring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRingRequest) Reset() {
	*x = SetRingRequest{}
	mi := &file_coordinator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRingRequest) ProtoMessage() {}

func (x *SetRingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRingRequest.ProtoReflect.Descriptor instead.
func (*SetRingRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{23}
}

func (x *SetRingRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetRingRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *SetRingRequest) GetRing() []*RingSlot {
	if x != nil {
		return x.Ring
	}
	return nil
}

type RegisterWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Definition    []byte                 `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"` // compiled graph JSON; content-hash => same version on every cell
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkflowRequest) Reset() {
	*x = RegisterWorkflowRequest{}
	mi := &file_coordinator_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowRequest) ProtoMessage() {}

func (x *RegisterWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{24}
}

func (x *RegisterWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterWorkflowRequest) GetDefinition() []byte {
	if x != nil {
		return x.Definition
	}
	return nil
}

type RegisterWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CellsSeeded   uint32                 `protobuf:"varint,2,opt,name=cells_seeded,json=cellsSeeded,proto3" json:"cells_seeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkflowResponse) Reset() {
	*x = RegisterWorkflowResponse{}
	mi := &file_coordinator_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowResponse) ProtoMessage() {}

func (x *RegisterWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{25}
}

func (x *RegisterWorkflowResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RegisterWorkflowResponse) GetCellsSeeded() uint32 {
	if x != nil {
		return x.CellsSeeded
	}
	return 0
}

type DeregisterWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterWorkflowRequest) Reset() {
	*x = DeregisterWorkflowRequest{}
	mi := &file_coordinator_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterWorkflowRequest) ProtoMessage() {}

func (x *DeregisterWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterWorkflowRequest.ProtoReflect.Descriptor instead.
func (*DeregisterWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{26}
}

func (x *DeregisterWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeregisterWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeregisterWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"` // false if the workflow was not allocated to the namespace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterWorkflowResponse) Reset() {
	*x = DeregisterWorkflowResponse{}
	mi := &file_coordinator_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterWorkflowResponse) ProtoMessage() {}

func (x *DeregisterWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterWorkflowResponse.ProtoReflect.Descriptor instead.
func (*DeregisterWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{27}
}

func (x *DeregisterWorkflowResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_coordinator_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{28}
}

func (x *ListWorkflowsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*AllocatedWorkflow   `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_coordinator_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{29}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*AllocatedWorkflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type AllocatedWorkflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"` // epoch millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocatedWorkflow) Reset() {
	*x = AllocatedWorkflow{}
	mi := &file_coordinator_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocatedWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocatedWorkflow) ProtoMessage() {}

func (x *AllocatedWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocatedWorkflow.ProtoReflect.Descriptor instead.
func (*AllocatedWorkflow) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{30}
}

func (x *AllocatedWorkflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AllocatedWorkflow) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AllocatedWorkflow) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

type Tuning_Memory struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SheddingEnabled *bool                  `protobuf:"varint,1,opt,name=shedding_enabled,json=sheddingEnabled,proto3,oneof" json:"shedding_enabled,omitempty"`
	Threshold       *float64               `protobuf:"fixed64,2,opt,name=threshold,proto3,oneof" json:"threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Tuning_Memory) Reset() {
	*x = Tuning_Memory{}
	mi := &file_coordinator_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuning_Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuning_Memory) ProtoMessage() {}

func (x *Tuning_Memory) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuning_Memory.ProtoReflect.Descriptor instead.
func (*Tuning_Memory) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Tuning_Memory) GetSheddingEnabled() bool {
	if x != nil && x.SheddingEnabled != nil {
		return *x.SheddingEnabled
	}
	return false
}

func (x *Tuning_Memory) GetThreshold() float64 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\x10dev.wiggle.proto\x1a\fwiggle.proto\"=\n" +
	"\x03Tls\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x15\n" +
	"\x06ca_ref\x18\x02 \x01(\tR\x05caRef\"\xa2\x01\n" +
	"\bEndpoint\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12'\n" +
	"\x03tls\x18\x03 \x01(\v2\x15.dev.wiggle.proto.TlsR\x03tls\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\"\x90\x01\n" +
	"\vStorageSpec\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x19\n" +
	"\bjdbc_url\x18\x02 \x01(\tR\ajdbcUrl\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"secret_ref\x18\x04 \x01(\tR\tsecretRef\x12\x1b\n" +
	"\tpool_size\x18\x05 \x01(\rR\bpoolSize\"\xde\x03\n" +
	"\x06Tuning\x125\n" +
	"\x14poll_interval_millis\x18\x01 \x01(\rH\x00R\x12pollIntervalMillis\x88\x01\x01\x12&\n" +
	"\flease_millis\x18\x02 \x01(\rH\x01R\vleaseMillis\x88\x01\x01\x124\n" +
	"\x14long_poll_max_millis\x18\x03 \x01(\rH\x02R\x11longPollMaxMillis\x88\x01\x01\x12.\n" +
	"\x10retention_millis\x18\x04 \x01(\x04H\x03R\x0fretentionMillis\x88\x01\x01\x127\n" +
	"\x06memory\x18\x05 \x01(\v2\x1f.dev.wiggle.proto.Tuning.MemoryR\x06memory\x1a~\n" +
	"\x06Memory\x12.\n" +
	"\x10shedding_enabled\x18\x01 \x01(\bH\x00R\x0fsheddingEnabled\x88\x01\x01\x12!\n" +
	"\tthreshold\x18\x02 \x01(\x01H\x01R\tthreshold\x88\x01\x01B\x13\n" +
	"\x11_shedding_enabledB\f\n" +
	"\n" +
	"_thresholdB\x17\n" +
	"\x15_poll_interval_millisB\x0f\n" +
	"\r_lease_millisB\x17\n" +
	"\x15_long_poll_max_millisB\x13\n" +
	"\x11_retention_millis\"Q\n" +
	"\bRingSlot\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"r\n" +
	"\tEpochRing\x12.\n" +
	"\x04ring\x18\x01 \x03(\v2\x1a.dev.wiggle.proto.RingSlotR\x04ring\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.dev.wiggle.proto.EpochStatusR\x06status\"\xfd\x01\n" +
	"\x06Policy\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rcurrent_epoch\x18\x02 \x01(\x04R\fcurrentEpoch\x12<\n" +
	"\x06epochs\x18\x03 \x03(\v2$.dev.wiggle.proto.Policy.EpochsEntryR\x06epochs\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x1aV\n" +
	"\vEpochsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.dev.wiggle.proto.EpochRingR\x05value:\x028\x01\"\x9d\x01\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion\x12%\n" +
	"\x0eadvertise_host\x18\x03 \x01(\tR\radvertiseHost\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x17\n" +
	"\acell_id\x18\x05 \x01(\tR\x06cellId\"b\n" +
	"\x12FetchConfigRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12.\n" +
	"\x04node\x18\x02 \x01(\v2\x1a.dev.wiggle.proto.NodeInfoR\x04node\"X\n" +
	"\bExpected\x12%\n" +
	"\x0eengine_version\x18\x01 \x01(\tR\rengineVersion\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\rR\rschemaVersion\"\xbc\x02\n" +
	"\n" +
	"NodeConfig\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x126\n" +
	"\bexpected\x18\x03 \x01(\v2\x1a.dev.wiggle.proto.ExpectedR\bexpected\x127\n" +
	"\astorage\x18\x04 \x01(\v2\x1d.dev.wiggle.proto.StorageSpecR\astorage\x120\n" +
	"\x06tuning\x18\x05 \x01(\v2\x18.dev.wiggle.proto.TuningR\x06tuning\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\rR\n" +
	"ttlSeconds\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x04R\x05epoch\x12\x16\n" +
	"\x06shards\x18\b \x03(\rR\x06shards\"\xb7\x01\n" +
	"\x0eRegisteredNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12%\n" +
	"\x0eengine_version\x18\x03 \x01(\tR\rengineVersion\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12\x17\n" +
	"\acell_id\x18\x06 \x01(\tR\x06cellId\"\x92\x01\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x124\n" +
	"\x04node\x18\x02 \x01(\v2 .dev.wiggle.proto.RegisteredNodeR\x04node\x12+\n" +
	"\x11config_generation\x18\x03 \x01(\x04R\x10configGeneration\"\xd4\x01\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\rR\x18heartbeatIntervalSeconds\x12;\n" +
	"\n" +
	"directives\x18\x03 \x03(\x0e2\x1b.dev.wiggle.proto.DirectiveR\n" +
	"directives\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x04R\x05epoch\x12\x16\n" +
	"\x06shards\x18\x05 \x03(\rR\x06shards\"\xcc\x01\n" +
	"\x06Health\x12\x1b\n" +
	"\tin_flight\x18\x01 \x01(\rR\binFlight\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\bR\x06leader\x12M\n" +
	"\rlive_by_epoch\x18\x03 \x03(\v2).dev.wiggle.proto.Health.LiveByEpochEntryR\vliveByEpoch\x1a>\n" +
	"\x10LiveByEpochEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\x95\x01\n" +
	"\x1bCoordinatorHeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12+\n" +
	"\x11config_generation\x18\x02 \x01(\x04R\x10configGeneration\x120\n" +
	"\x06health\x18\x03 \x01(\v2\x18.dev.wiggle.proto.HealthR\x06health\"\x98\x01\n" +
	"\x1cCoordinatorHeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12+\n" +
	"\x11config_generation\x18\x02 \x01(\x04R\x10configGeneration\x12;\n" +
	"\n" +
	"directives\x18\x03 \x03(\x0e2\x1b.dev.wiggle.proto.DirectiveR\n" +
	"directives\",\n" +
	"\x11DeregisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"~\n" +
	"\x0eResolveRequest\x12!\n" +
	"\vinstance_id\x18\x01 \x01(\tH\x00R\n" +
	"instanceId\x12\x1e\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x12#\n" +
	"\rcaller_region\x18\x03 \x01(\tR\fcallerRegionB\x04\n" +
	"\x02by\"\x9e\x01\n" +
	"\x0fResolveResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x126\n" +
	"\bendpoint\x18\x03 \x01(\v2\x1a.dev.wiggle.proto.EndpointR\bendpoint\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\rR\n" +
	"ttlSeconds\"W\n" +
	"\x12ActiveCellsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rcaller_region\x18\x02 \x01(\tR\fcallerRegion\"\x88\x01\n" +
	"\x13ActiveCellsResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x120\n" +
	"\x05cells\x18\x02 \x03(\v2\x1a.dev.wiggle.proto.EndpointR\x05cells\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\rR\n" +
	"ttlSeconds\"`\n" +
	"\x10OpenEpochRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12.\n" +
	"\x04ring\x18\x02 \x03(\v2\x1a.dev.wiggle.proto.RingSlotR\x04ring\"t\n" +
	"\x0eSetRingRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12.\n" +
	"\x04ring\x18\x03 \x03(\v2\x1a.dev.wiggle.proto.RingSlotR\x04ring\"k\n" +
	"\x17RegisterWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"definition\x18\x03 \x01(\fR\n" +
	"definition\"W\n" +
	"\x18RegisterWorkflowResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12!\n" +
	"\fcells_seeded\x18\x02 \x01(\rR\vcellsSeeded\"M\n" +
	"\x19DeregisterWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\x1aDeregisterWorkflowResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"4\n" +
	"\x14ListWorkflowsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"Z\n" +
	"\x15ListWorkflowsResponse\x12A\n" +
	"\tworkflows\x18\x01 \x03(\v2#.dev.wiggle.proto.AllocatedWorkflowR\tworkflows\"f\n" +
	"\x11AllocatedWorkflow\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12#\n" +
	"\rregistered_at\x18\x03 \x01(\x03R\fregisteredAt*P\n" +
	"\vEpochStatus\x12\x1c\n" +
	"\x18EPOCH_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\f\n" +
	"\bDRAINING\x10\x02\x12\v\n" +
	"\aRETIRED\x10\x03*B\n" +
	"\tDirective\x12\x19\n" +
	"\x15DIRECTIVE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vRECONFIGURE\x10\x01\x12\t\n" +
	"\x05DRAIN\x10\x022\xeb\a\n" +
	"\x0fCellCoordinator\x12Q\n" +
	"\vFetchConfig\x12$.dev.wiggle.proto.FetchConfigRequest\x1a\x1c.dev.wiggle.proto.NodeConfig\x12Q\n" +
	"\bRegister\x12!.dev.wiggle.proto.RegisterRequest\x1a\".dev.wiggle.proto.RegisterResponse\x12j\n" +
	"\tHeartbeat\x12-.dev.wiggle.proto.CoordinatorHeartbeatRequest\x1a..dev.wiggle.proto.CoordinatorHeartbeatResponse\x12J\n" +
	"\n" +
	"Deregister\x12#.dev.wiggle.proto.DeregisterRequest\x1a\x17.dev.wiggle.proto.Empty\x12N\n" +
	"\aResolve\x12 .dev.wiggle.proto.ResolveRequest\x1a!.dev.wiggle.proto.ResolveResponse\x12Z\n" +
	"\vActiveCells\x12$.dev.wiggle.proto.ActiveCellsRequest\x1a%.dev.wiggle.proto.ActiveCellsResponse\x12I\n" +
	"\tOpenEpoch\x12\".dev.wiggle.proto.OpenEpochRequest\x1a\x18.dev.wiggle.proto.Policy\x12E\n" +
	"\aSetRing\x12 .dev.wiggle.proto.SetRingRequest\x1a\x18.dev.wiggle.proto.Policy\x12i\n" +
	"\x10RegisterWorkflow\x12).dev.wiggle.proto.RegisterWorkflowRequest\x1a*.dev.wiggle.proto.RegisterWorkflowResponse\x12o\n" +
	"\x12DeregisterWorkflow\x12+.dev.wiggle.proto.DeregisterWorkflowRequest\x1a,.dev.wiggle.proto.DeregisterWorkflowResponse\x12`\n" +
	"\rListWorkflows\x12&.dev.wiggle.proto.ListWorkflowsRequest\x1a'.dev.wiggle.proto.ListWorkflowsResponseBE\n" +
	"\x10dev.wiggle.protoP\x01Z/github.com/hadielmougy/wiggle-go/internal/pb;pbb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_coordinator_proto_goTypes = []any{
	(EpochStatus)(0),                     // 0: dev.wiggle.proto.EpochStatus
	(Directive)(0),                       // 1: dev.wiggle.proto.Directive
	(*Tls)(nil),                          // 2: dev.wiggle.proto.Tls
	(*Endpoint)(nil),                     // 3: dev.wiggle.proto.Endpoint
	(*StorageSpec)(nil),                  // 4: dev.wiggle.proto.StorageSpec
	(*Tuning)(nil),                       // 5: dev.wiggle.proto.Tuning
	(*RingSlot)(nil),                     // 6: dev.wiggle.proto.RingSlot
	(*EpochRing)(nil),                    // 7: dev.wiggle.proto.EpochRing
	(*Policy)(nil),                       // 8: dev.wiggle.proto.Policy
	(*NodeInfo)(nil),                     // 9: dev.wiggle.proto.NodeInfo
	(*FetchConfigRequest)(nil),           // 10: dev.wiggle.proto.FetchConfigRequest
	(*Expected)(nil),                     // 11: dev.wiggle.proto.Expected
	(*NodeConfig)(nil),                   // 12: dev.wiggle.proto.NodeConfig
	(*RegisteredNode)(nil),               // 13: dev.wiggle.proto.RegisteredNode
	(*RegisterRequest)(nil),              // 14: dev.wiggle.proto.RegisterRequest
	(*RegisterResponse)(nil),             // 15: dev.wiggle.proto.RegisterResponse
	(*Health)(nil),                       // 16: dev.wiggle.proto.Health
	(*CoordinatorHeartbeatRequest)(nil),  // 17: dev.wiggle.proto.CoordinatorHeartbeatRequest
	(*CoordinatorHeartbeatResponse)(nil), // 18: dev.wiggle.proto.CoordinatorHeartbeatResponse
	(*DeregisterRequest)(nil),            // 19: dev.wiggle.proto.DeregisterRequest
	(*ResolveRequest)(nil),               // 20: dev.wiggle.proto.ResolveRequest
	(*ResolveResponse)(nil),              // 21: dev.wiggle.proto.ResolveResponse
	(*ActiveCellsRequest)(nil),           // 22: dev.wiggle.proto.ActiveCellsRequest
	(*ActiveCellsResponse)(nil),          // 23: dev.wiggle.proto.ActiveCellsResponse
	(*OpenEpochRequest)(nil),             // 24: dev.wiggle.proto.OpenEpochRequest
	(*SetRingRequest)(nil),               // 25: dev.wiggle.proto.SetRingRequest
	(*RegisterWorkflowRequest)(nil),      // 26: dev.wiggle.proto.RegisterWorkflowRequest
	(*RegisterWorkflowResponse)(nil),     // 27: dev.wiggle.proto.RegisterWorkflowResponse
	(*DeregisterWorkflowRequest)(nil),    // 28: dev.wiggle.proto.DeregisterWorkflowRequest
	(*DeregisterWorkflowResponse)(nil),   // 29: dev.wiggle.proto.DeregisterWorkflowResponse
	(*ListWorkflowsRequest)(nil),         // 30: dev.wiggle.proto.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),        // 31: dev.wiggle.proto.ListWorkflowsResponse
	(*AllocatedWorkflow)(nil),            // 32: dev.wiggle.proto.AllocatedWorkflow
	(*Tuning_Memory)(nil),                // 33: dev.wiggle.proto.Tuning.Memory
	nil,                                  // 34: dev.wiggle.proto.Policy.EpochsEntry
	nil,                                  // 35: dev.wiggle.proto.Health.LiveByEpochEntry
	(*Empty)(nil),                        // 36: dev.wiggle.proto.Empty
}
var file_coordinator_proto_depIdxs = []int32{
	2,  // 0: dev.wiggle.proto.Endpoint.tls:type_name -> dev.wiggle.proto.Tls
	33, // 1: dev.wiggle.proto.Tuning.memory:type_name -> dev.wiggle.proto.Tuning.Memory
	6,  // 2: dev.wiggle.proto.EpochRing.ring:type_name -> dev.wiggle.proto.RingSlot
	0,  // 3: dev.wiggle.proto.EpochRing.status:type_name -> dev.wiggle.proto.EpochStatus
	34, // 4: dev.wiggle.proto.Policy.epochs:type_name -> dev.wiggle.proto.Policy.EpochsEntry
	9,  // 5: dev.wiggle.proto.FetchConfigRequest.node:type_name -> dev.wiggle.proto.NodeInfo
	11, // 6: dev.wiggle.proto.NodeConfig.expected:type_name -> dev.wiggle.proto.Expected
	4,  // 7: dev.wiggle.proto.NodeConfig.storage:type_name -> dev.wiggle.proto.StorageSpec
	5,  // 8: dev.wiggle.proto.NodeConfig.tuning:type_name -> dev.wiggle.proto.Tuning
	13, // 9: dev.wiggle.proto.RegisterRequest.node:type_name -> dev.wiggle.proto.RegisteredNode
	1,  // 10: dev.wiggle.proto.RegisterResponse.directives:type_name -> dev.wiggle.proto.Directive
	35, // 11: dev.wiggle.proto.Health.live_by_epoch:type_name -> dev.wiggle.proto.Health.LiveByEpochEntry
	16, // 12: dev.wiggle.proto.CoordinatorHeartbeatRequest.health:type_name -> dev.wiggle.proto.Health
	1,  // 13: dev.wiggle.proto.CoordinatorHeartbeatResponse.directives:type_name -> dev.wiggle.proto.Directive
	3,  // 14: dev.wiggle.proto.ResolveResponse.endpoint:type_name -> dev.wiggle.proto.Endpoint
	3,  // 15: dev.wiggle.proto.ActiveCellsResponse.cells:type_name -> dev.wiggle.proto.Endpoint
	6,  // 16: dev.wiggle.proto.OpenEpochRequest.ring:type_name -> dev.wiggle.proto.RingSlot
	6,  // 17: dev.wiggle.proto.SetRingRequest.ring:type_name -> dev.wiggle.proto.RingSlot
	32, // 18: dev.wiggle.proto.ListWorkflowsResponse.workflows:type_name -> dev.wiggle.proto.AllocatedWorkflow
	7,  // 19: dev.wiggle.proto.Policy.EpochsEntry.value:type_name -> dev.wiggle.proto.EpochRing
	10, // 20: dev.wiggle.proto.CellCoordinator.FetchConfig:input_type -> dev.wiggle.proto.FetchConfigRequest
	14, // 21: dev.wiggle.proto.CellCoordinator.Register:input_type -> dev.wiggle.proto.RegisterRequest
	17, // 22: dev.wiggle.proto.CellCoordinator.Heartbeat:input_type -> dev.wiggle.proto.CoordinatorHeartbeatRequest
	19, // 23: dev.wiggle.proto.CellCoordinator.Deregister:input_type -> dev.wiggle.proto.DeregisterRequest
	20, // 24: dev.wiggle.proto.CellCoordinator.Resolve:input_type -> dev.wiggle.proto.ResolveRequest
	22, // 25: dev.wiggle.proto.CellCoordinator.ActiveCells:input_type -> dev.wiggle.proto.ActiveCellsRequest
	24, // 26: dev.wiggle.proto.CellCoordinator.OpenEpoch:input_type -> dev.wiggle.proto.OpenEpochRequest
	25, // 27: dev.wiggle.proto.CellCoordinator.SetRing:input_type -> dev.wiggle.proto.SetRingRequest
	26, // 28: dev.wiggle.proto.CellCoordinator.RegisterWorkflow:input_type -> dev.wiggle.proto.RegisterWorkflowRequest
	28, // 29: dev.wiggle.proto.CellCoordinator.DeregisterWorkflow:input_type -> dev.wiggle.proto.DeregisterWorkflowRequest
	30, // 30: dev.wiggle.proto.CellCoordinator.ListWorkflows:input_type -> dev.wiggle.proto.ListWorkflowsRequest
	12, // 31: dev.wiggle.proto.CellCoordinator.FetchConfig:output_type -> dev.wiggle.proto.NodeConfig
	15, // 32: dev.wiggle.proto.CellCoordinator.Register:output_type -> dev.wiggle.proto.RegisterResponse
	18, // 33: dev.wiggle.proto.CellCoordinator.Heartbeat:output_type -> dev.wiggle.proto.CoordinatorHeartbeatResponse
	36, // 34: dev.wiggle.proto.CellCoordinator.Deregister:output_type -> dev.wiggle.proto.Empty
	21, // 35: dev.wiggle.proto.CellCoordinator.Resolve:output_type -> dev.wiggle.proto.ResolveResponse
	23, // 36: dev.wiggle.proto.CellCoordinator.ActiveCells:output_type -> dev.wiggle.proto.ActiveCellsResponse
	8,  // 37: dev.wiggle.proto.CellCoordinator.OpenEpoch:output_type -> dev.wiggle.proto.Policy
	8,  // 38: dev.wiggle.proto.CellCoordinator.SetRing:output_type -> dev.wiggle.proto.Policy
	27, // 39: dev.wiggle.proto.CellCoordinator.RegisterWorkflow:output_type -> dev.wiggle.proto.RegisterWorkflowResponse
	29, // 40: dev.wiggle.proto.CellCoordinator.DeregisterWorkflow:output_type -> dev.wiggle.proto.DeregisterWorkflowResponse
	31, // 41: dev.wiggle.proto.CellCoordinator.ListWorkflows:output_type -> dev.wiggle.proto.ListWorkflowsResponse
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	file_wiggle_proto_init()
	file_coordinator_proto_msgTypes[3].OneofWrappers = []any{}
	file_coordinator_proto_msgTypes[18].OneofWrappers = []any{
		(*ResolveRequest_InstanceId)(nil),
		(*ResolveRequest_Namespace)(nil),
	}
	file_coordinator_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		EnumInfos:         file_coordinator_proto_enumTypes,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
