// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: wiggle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_wiggle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{0}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_wiggle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Leader        bool                   `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_wiggle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{2}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *HealthStatus) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

type ClusterMember struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FirstHeartbeat int64                  `protobuf:"varint,3,opt,name=first_heartbeat,json=firstHeartbeat,proto3" json:"first_heartbeat,omitempty"`
	LastHeartbeat  int64                  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Workers        int32                  `protobuf:"varint,5,opt,name=workers,proto3" json:"workers,omitempty"`
	Leader         bool                   `protobuf:"varint,6,opt,name=leader,proto3" json:"leader,omitempty"`
	Alive          bool                   `protobuf:"varint,7,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterMember) Reset() {
	*x = ClusterMember{}
	mi := &file_wiggle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMember) ProtoMessage() {}

func (x *ClusterMember) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMember.ProtoReflect.Descriptor instead.
func (*ClusterMember) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterMember) GetFirstHeartbeat() int64 {
	if x != nil {
		return x.FirstHeartbeat
	}
	return 0
}

func (x *ClusterMember) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *ClusterMember) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *ClusterMember) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *ClusterMember) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type ClusterView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          string                 `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Leader        bool                   `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Members       []*ClusterMember       `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterView) Reset() {
	*x = ClusterView{}
	mi := &file_wiggle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterView) ProtoMessage() {}

func (x *ClusterView) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterView.ProtoReflect.Descriptor instead.
func (*ClusterView) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterView) GetSelf() string {
	if x != nil {
		return x.Self
	}
	return ""
}

func (x *ClusterView) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *ClusterView) GetMembers() []*ClusterMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type WorkflowDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *structpb.Struct       `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinition) Reset() {
	*x = WorkflowDefinition{}
	mi := &file_wiggle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinition) ProtoMessage() {}

func (x *WorkflowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinition.ProtoReflect.Descriptor instead.
func (*WorkflowDefinition) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowDefinition) GetDefinition() *structpb.Struct {
	if x != nil {
		return x.Definition
	}
	return nil
}

type WorkflowNames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []string               `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowNames) Reset() {
	*x = WorkflowNames{}
	mi := &file_wiggle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowNames) ProtoMessage() {}

func (x *WorkflowNames) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowNames.ProtoReflect.Descriptor instead.
func (*WorkflowNames) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowNames) GetWorkflows() []string {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type RegisterWorkflowResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Nodes         int64                  `protobuf:"varint,3,opt,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkflowResult) Reset() {
	*x = RegisterWorkflowResult{}
	mi := &file_wiggle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowResult) ProtoMessage() {}

func (x *RegisterWorkflowResult) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowResult.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowResult) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterWorkflowResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterWorkflowResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterWorkflowResult) GetNodes() int64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_wiggle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      string                 `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Context       *structpb.Value        `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Version       *int32                 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	CorrelationId *string                `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3,oneof" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_wiggle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{9}
}

func (x *StartInstanceRequest) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *StartInstanceRequest) GetContext() *structpb.Value {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StartInstanceRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *StartInstanceRequest) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

type StartInstanceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Workflow      string                 `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceResult) Reset() {
	*x = StartInstanceResult{}
	mi := &file_wiggle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceResult) ProtoMessage() {}

func (x *StartInstanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceResult.ProtoReflect.Descriptor instead.
func (*StartInstanceResult) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{10}
}

func (x *StartInstanceResult) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartInstanceResult) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

type InstanceView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workflow          string                 `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Version           int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TerminationReason *string                `protobuf:"bytes,5,opt,name=termination_reason,json=terminationReason,proto3,oneof" json:"termination_reason,omitempty"`
	Error             *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Context           *structpb.Value        `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstanceView) Reset() {
	*x = InstanceView{}
	mi := &file_wiggle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceView) ProtoMessage() {}

func (x *InstanceView) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceView.ProtoReflect.Descriptor instead.
func (*InstanceView) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{11}
}

func (x *InstanceView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceView) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *InstanceView) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InstanceView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceView) GetTerminationReason() string {
	if x != nil && x.TerminationReason != nil {
		return *x.TerminationReason
	}
	return ""
}

func (x *InstanceView) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *InstanceView) GetContext() *structpb.Value {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *InstanceView) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *InstanceView) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Activity      string                 `protobuf:"bytes,5,opt,name=activity,proto3" json:"activity,omitempty"`
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	AvailableAt   int64                  `protobuf:"varint,7,opt,name=available_at,json=availableAt,proto3" json:"available_at,omitempty"`
	LeaseOwner    *string                `protobuf:"bytes,8,opt,name=lease_owner,json=leaseOwner,proto3,oneof" json:"lease_owner,omitempty"`
	LastError     *string                `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3,oneof" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_wiggle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{12}
}

func (x *Token) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Token) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Token) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Token) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Token) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *Token) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Token) GetAvailableAt() int64 {
	if x != nil {
		return x.AvailableAt
	}
	return 0
}

func (x *Token) GetLeaseOwner() string {
	if x != nil && x.LeaseOwner != nil {
		return *x.LeaseOwner
	}
	return ""
}

func (x *Token) GetLastError() string {
	if x != nil && x.LastError != nil {
		return *x.LastError
	}
	return ""
}

type InstanceDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *InstanceView          `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Tokens        []*Token               `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceDetail) Reset() {
	*x = InstanceDetail{}
	mi := &file_wiggle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceDetail) ProtoMessage() {}

func (x *InstanceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceDetail.ProtoReflect.Descriptor instead.
func (*InstanceDetail) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{13}
}

func (x *InstanceDetail) GetInstance() *InstanceView {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *InstanceDetail) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type ListInstancesRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Workflow *string                `protobuf:"bytes,1,opt,name=workflow,proto3,oneof" json:"workflow,omitempty"`
	Status   *string                `protobuf:"bytes,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Limit    int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// When set, return only instances started with this correlation id (business key lookup).
	CorrelationId *string `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3,oneof" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_wiggle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{14}
}

func (x *ListInstancesRequest) GetWorkflow() string {
	if x != nil && x.Workflow != nil {
		return *x.Workflow
	}
	return ""
}

func (x *ListInstancesRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListInstancesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInstancesRequest) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

type InstanceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*InstanceView        `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceList) Reset() {
	*x = InstanceList{}
	mi := &file_wiggle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceList) ProtoMessage() {}

func (x *InstanceList) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceList.ProtoReflect.Descriptor instead.
func (*InstanceList) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{15}
}

func (x *InstanceList) GetInstances() []*InstanceView {
	if x != nil {
		return x.Instances
	}
	return nil
}

type InstanceIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceIdRequest) Reset() {
	*x = InstanceIdRequest{}
	mi := &file_wiggle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceIdRequest) ProtoMessage() {}

func (x *InstanceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceIdRequest.ProtoReflect.Descriptor instead.
func (*InstanceIdRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{16}
}

func (x *InstanceIdRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type CancelInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInstanceRequest) Reset() {
	*x = CancelInstanceRequest{}
	mi := &file_wiggle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInstanceRequest) ProtoMessage() {}

func (x *CancelInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInstanceRequest.ProtoReflect.Descriptor instead.
func (*CancelInstanceRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{17}
}

func (x *CancelInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CancelInstanceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	Payload       *structpb.Value        `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_wiggle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{18}
}

func (x *SignalRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SignalRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *SignalRequest) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateScheduleRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Workflow string                 `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	// Types that are valid to be assigned to Cadence:
	//
	//	*CreateScheduleRequest_EveryMillis
	//	*CreateScheduleRequest_Cron
	Cadence       isCreateScheduleRequest_Cadence `protobuf_oneof:"cadence"`
	Context       *structpb.Value                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_wiggle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{19}
}

func (x *CreateScheduleRequest) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *CreateScheduleRequest) GetCadence() isCreateScheduleRequest_Cadence {
	if x != nil {
		return x.Cadence
	}
	return nil
}

func (x *CreateScheduleRequest) GetEveryMillis() int64 {
	if x != nil {
		if x, ok := x.Cadence.(*CreateScheduleRequest_EveryMillis); ok {
			return x.EveryMillis
		}
	}
	return 0
}

func (x *CreateScheduleRequest) GetCron() string {
	if x != nil {
		if x, ok := x.Cadence.(*CreateScheduleRequest_Cron); ok {
			return x.Cron
		}
	}
	return ""
}

func (x *CreateScheduleRequest) GetContext() *structpb.Value {
	if x != nil {
		return x.Context
	}
	return nil
}

type isCreateScheduleRequest_Cadence interface {
	isCreateScheduleRequest_Cadence()
}

type CreateScheduleRequest_EveryMillis struct {
	EveryMillis int64 `protobuf:"varint,2,opt,name=every_millis,json=everyMillis,proto3,oneof"` // fixed interval
}

type CreateScheduleRequest_Cron struct {
	Cron string `protobuf:"bytes,3,opt,name=cron,proto3,oneof"` // five-field cron, evaluated in UTC
}

func (*CreateScheduleRequest_EveryMillis) isCreateScheduleRequest_Cadence() {}

func (*CreateScheduleRequest_Cron) isCreateScheduleRequest_Cadence() {}

type ScheduleView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workflow      string                 `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	EveryMillis   int64                  `protobuf:"varint,3,opt,name=every_millis,json=everyMillis,proto3" json:"every_millis,omitempty"` // 0 when cron-based
	Cron          string                 `protobuf:"bytes,4,opt,name=cron,proto3" json:"cron,omitempty"`                                   // empty when interval-based
	NextFireAt    int64                  `protobuf:"varint,5,opt,name=next_fire_at,json=nextFireAt,proto3" json:"next_fire_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleView) Reset() {
	*x = ScheduleView{}
	mi := &file_wiggle_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleView) ProtoMessage() {}

func (x *ScheduleView) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleView.ProtoReflect.Descriptor instead.
func (*ScheduleView) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{20}
}

func (x *ScheduleView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleView) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *ScheduleView) GetEveryMillis() int64 {
	if x != nil {
		return x.EveryMillis
	}
	return 0
}

func (x *ScheduleView) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *ScheduleView) GetNextFireAt() int64 {
	if x != nil {
		return x.NextFireAt
	}
	return 0
}

func (x *ScheduleView) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ScheduleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*ScheduleView        `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleList) Reset() {
	*x = ScheduleList{}
	mi := &file_wiggle_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleList) ProtoMessage() {}

func (x *ScheduleList) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleList.ProtoReflect.Descriptor instead.
func (*ScheduleList) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{21}
}

func (x *ScheduleList) GetSchedules() []*ScheduleView {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type ScheduleIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleIdRequest) Reset() {
	*x = ScheduleIdRequest{}
	mi := &file_wiggle_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleIdRequest) ProtoMessage() {}

func (x *ScheduleIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleIdRequest.ProtoReflect.Descriptor instead.
func (*ScheduleIdRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{22}
}

func (x *ScheduleIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelInstanceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     string                 `protobuf:"bytes,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInstanceResult) Reset() {
	*x = CancelInstanceResult{}
	mi := &file_wiggle_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInstanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInstanceResult) ProtoMessage() {}

func (x *CancelInstanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInstanceResult.ProtoReflect.Descriptor instead.
func (*CancelInstanceResult) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{23}
}

func (x *CancelInstanceResult) GetCancelled() string {
	if x != nil {
		return x.Cancelled
	}
	return ""
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Queues        []string               `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"`
	Max           int32                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	LeaseMillis   int64                  `protobuf:"varint,4,opt,name=lease_millis,json=leaseMillis,proto3" json:"lease_millis,omitempty"`
	WaitMillis    int64                  `protobuf:"varint,5,opt,name=wait_millis,json=waitMillis,proto3" json:"wait_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_wiggle_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{24}
}

func (x *PollRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PollRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *PollRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *PollRequest) GetLeaseMillis() int64 {
	if x != nil {
		return x.LeaseMillis
	}
	return 0
}

func (x *PollRequest) GetWaitMillis() int64 {
	if x != nil {
		return x.WaitMillis
	}
	return 0
}

type TaskActivation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	InstanceId     string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Workflow       string                 `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Version        int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	NodeId         string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	StepName       string                 `protobuf:"bytes,6,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Activity       string                 `protobuf:"bytes,7,opt,name=activity,proto3" json:"activity,omitempty"`
	Kind           string                 `protobuf:"bytes,8,opt,name=kind,proto3" json:"kind,omitempty"`
	Attempt        int32                  `protobuf:"varint,9,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LeaseExpiresAt int64                  `protobuf:"varint,10,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	LeaseOwner     string                 `protobuf:"bytes,11,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	Context        *structpb.Value        `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
	ExecutionMode  string                 `protobuf:"bytes,13,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"` // SERVER | LOCAL_SYNC | LOCAL_ASYNC (already resolved by the server)
	// Set only for a forEach item step: `context` is then the ITEM's current value (any JSON value,
	// scalars included), and base_context is the frozen pre-forEach context (read-only for items).
	BaseContext   *structpb.Value `protobuf:"bytes,14,opt,name=base_context,json=baseContext,proto3" json:"base_context,omitempty"`
	ItemIndex     int64           `protobuf:"varint,15,opt,name=item_index,json=itemIndex,proto3" json:"item_index,omitempty"`     // the item's position in the input collection
	ItemMapKey    string          `protobuf:"bytes,16,opt,name=item_map_key,json=itemMapKey,proto3" json:"item_map_key,omitempty"` // the item's source key, when the input collection was a map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskActivation) Reset() {
	*x = TaskActivation{}
	mi := &file_wiggle_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskActivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskActivation) ProtoMessage() {}

func (x *TaskActivation) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskActivation.ProtoReflect.Descriptor instead.
func (*TaskActivation) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{25}
}

func (x *TaskActivation) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskActivation) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *TaskActivation) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *TaskActivation) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TaskActivation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskActivation) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *TaskActivation) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *TaskActivation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TaskActivation) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskActivation) GetLeaseExpiresAt() int64 {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return 0
}

func (x *TaskActivation) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *TaskActivation) GetContext() *structpb.Value {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *TaskActivation) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

func (x *TaskActivation) GetBaseContext() *structpb.Value {
	if x != nil {
		return x.BaseContext
	}
	return nil
}

func (x *TaskActivation) GetItemIndex() int64 {
	if x != nil {
		return x.ItemIndex
	}
	return 0
}

func (x *TaskActivation) GetItemMapKey() string {
	if x != nil {
		return x.ItemMapKey
	}
	return ""
}

type TaskList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tasks []*TaskActivation      `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// Backpressure hint: when > 0 the server is shedding load (it is over its memory threshold), so
	// the worker should hold off this many millis before polling again instead of retrying
	// immediately. The value already includes per-response jitter.
	RetryAfterMillis int64 `protobuf:"varint,2,opt,name=retry_after_millis,json=retryAfterMillis,proto3" json:"retry_after_millis,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	mi := &file_wiggle_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{26}
}

func (x *TaskList) GetTasks() []*TaskActivation {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TaskList) GetRetryAfterMillis() int64 {
	if x != nil {
		return x.RetryAfterMillis
	}
	return 0
}

// One locally-executed step reported back to the server (LOCAL_SYNC/LOCAL_ASYNC).
type StepResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*StepResult_Merge
	//	*StepResult_PredicateValue
	Outcome       isStepResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_wiggle_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{27}
}

func (x *StepResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StepResult) GetOutcome() isStepResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *StepResult) GetMerge() *structpb.Value {
	if x != nil {
		if x, ok := x.Outcome.(*StepResult_Merge); ok {
			return x.Merge
		}
	}
	return nil
}

func (x *StepResult) GetPredicateValue() bool {
	if x != nil {
		if x, ok := x.Outcome.(*StepResult_PredicateValue); ok {
			return x.PredicateValue
		}
	}
	return false
}

type isStepResult_Outcome interface {
	isStepResult_Outcome()
}

type StepResult_Merge struct {
	Merge *structpb.Value `protobuf:"bytes,2,opt,name=merge,proto3,oneof"` // TASK: shallow diff to merge into context
}

type StepResult_PredicateValue struct {
	PredicateValue bool `protobuf:"varint,3,opt,name=predicate_value,json=predicateValue,proto3,oneof"` // PREDICATE: branch selector
}

func (*StepResult_Merge) isStepResult_Outcome() {}

func (*StepResult_PredicateValue) isStepResult_Outcome() {}

type AdvanceRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // the currently-leased token being completed
	LeaseOwner    string                 `protobuf:"bytes,2,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	Steps         []*StepResult          `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`  // ordered; one step for LOCAL_SYNC
	Final         bool                   `protobuf:"varint,4,opt,name=final,proto3" json:"final,omitempty"` // true = worker reached a boundary and is handing back
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvanceRunRequest) Reset() {
	*x = AdvanceRunRequest{}
	mi := &file_wiggle_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceRunRequest) ProtoMessage() {}

func (x *AdvanceRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceRunRequest.ProtoReflect.Descriptor instead.
func (*AdvanceRunRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{28}
}

func (x *AdvanceRunRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AdvanceRunRequest) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *AdvanceRunRequest) GetSteps() []*StepResult {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *AdvanceRunRequest) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type AdvanceRunResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceStatus string                 `protobuf:"bytes,1,opt,name=instance_status,json=instanceStatus,proto3" json:"instance_status,omitempty"`    // RUNNING | COMPLETED | FAILED | CANCELLED
	LeaseExpiresAt int64                  `protobuf:"varint,2,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"` // renewed lease covering continued local execution
	NextTaskId     string                 `protobuf:"bytes,3,opt,name=next_task_id,json=nextTaskId,proto3" json:"next_task_id,omitempty"`              // token to reference for the next local step (blank if handed back)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdvanceRunResult) Reset() {
	*x = AdvanceRunResult{}
	mi := &file_wiggle_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceRunResult) ProtoMessage() {}

func (x *AdvanceRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceRunResult.ProtoReflect.Descriptor instead.
func (*AdvanceRunResult) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{29}
}

func (x *AdvanceRunResult) GetInstanceStatus() string {
	if x != nil {
		return x.InstanceStatus
	}
	return ""
}

func (x *AdvanceRunResult) GetLeaseExpiresAt() int64 {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return 0
}

func (x *AdvanceRunResult) GetNextTaskId() string {
	if x != nil {
		return x.NextTaskId
	}
	return ""
}

type TaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseOwner    string                 `protobuf:"bytes,2,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	Result        *structpb.Value        `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultRequest) Reset() {
	*x = TaskResultRequest{}
	mi := &file_wiggle_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultRequest) ProtoMessage() {}

func (x *TaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultRequest.ProtoReflect.Descriptor instead.
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{30}
}

func (x *TaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultRequest) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *TaskResultRequest) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

type TaskFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseOwner    string                 `protobuf:"bytes,2,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFailureRequest) Reset() {
	*x = TaskFailureRequest{}
	mi := &file_wiggle_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFailureRequest) ProtoMessage() {}

func (x *TaskFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFailureRequest.ProtoReflect.Descriptor instead.
func (*TaskFailureRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{31}
}

func (x *TaskFailureRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskFailureRequest) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *TaskFailureRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskFailureRequest) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseOwner    string                 `protobuf:"bytes,2,opt,name=lease_owner,json=leaseOwner,proto3" json:"lease_owner,omitempty"`
	ExtendMillis  int64                  `protobuf:"varint,3,opt,name=extend_millis,json=extendMillis,proto3" json:"extend_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_wiggle_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{32}
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatRequest) GetLeaseOwner() string {
	if x != nil {
		return x.LeaseOwner
	}
	return ""
}

func (x *HeartbeatRequest) GetExtendMillis() int64 {
	if x != nil {
		return x.ExtendMillis
	}
	return 0
}

type HeartbeatResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LeaseExpiresAt int64                  `protobuf:"varint,1,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResult) Reset() {
	*x = HeartbeatResult{}
	mi := &file_wiggle_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResult) ProtoMessage() {}

func (x *HeartbeatResult) ProtoReflect() protoreflect.Message {
	mi := &file_wiggle_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResult.ProtoReflect.Descriptor instead.
func (*HeartbeatResult) Descriptor() ([]byte, []int) {
	return file_wiggle_proto_rawDescGZIP(), []int{33}
}

func (x *HeartbeatResult) GetLeaseExpiresAt() int64 {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return 0
}

var File_wiggle_proto protoreflect.FileDescriptor

const file_wiggle_proto_rawDesc = "" +
	"\n" +
	"\fwiggle.proto\x12\x10com.wiggle.proto\x1a\x1cgoogle/protobuf/struct.proto\"\a\n" +
	"\x05Empty\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"R\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\bR\x06leader\"\xcb\x01\n" +
	"\rClusterMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0ffirst_heartbeat\x18\x03 \x01(\x03R\x0efirstHeartbeat\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\x03R\rlastHeartbeat\x12\x18\n" +
	"\aworkers\x18\x05 \x01(\x05R\aworkers\x12\x16\n" +
	"\x06leader\x18\x06 \x01(\bR\x06leader\x12\x14\n" +
	"\x05alive\x18\a \x01(\bR\x05alive\"t\n" +
	"\vClusterView\x12\x12\n" +
	"\x04self\x18\x01 \x01(\tR\x04self\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\bR\x06leader\x129\n" +
	"\amembers\x18\x03 \x03(\v2\x1f.com.wiggle.proto.ClusterMemberR\amembers\"M\n" +
	"\x12WorkflowDefinition\x127\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"definition\"-\n" +
	"\rWorkflowNames\x12\x1c\n" +
	"\tworkflows\x18\x01 \x03(\tR\tworkflows\"\\\n" +
	"\x16RegisterWorkflowResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05nodes\x18\x03 \x01(\x03R\x05nodes\"(\n" +
	"\x12GetWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xce\x01\n" +
	"\x14StartInstanceRequest\x12\x1a\n" +
	"\bworkflow\x18\x01 \x01(\tR\bworkflow\x120\n" +
	"\acontext\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\acontext\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x05H\x00R\aversion\x88\x01\x01\x12*\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tH\x01R\rcorrelationId\x88\x01\x01B\n" +
	"\n" +
	"\b_versionB\x11\n" +
	"\x0f_correlation_id\"R\n" +
	"\x13StartInstanceResult\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bworkflow\x18\x02 \x01(\tR\bworkflow\"\xcc\x02\n" +
	"\fInstanceView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bworkflow\x18\x02 \x01(\tR\bworkflow\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x122\n" +
	"\x12termination_reason\x18\x05 \x01(\tH\x00R\x11terminationReason\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x01R\x05error\x88\x01\x01\x120\n" +
	"\acontext\x18\a \x01(\v2\x16.google.protobuf.ValueR\acontext\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAtB\x15\n" +
	"\x13_termination_reasonB\b\n" +
	"\x06_error\"\x9e\x02\n" +
	"\x05Token\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bactivity\x18\x05 \x01(\tR\bactivity\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12!\n" +
	"\favailable_at\x18\a \x01(\x03R\vavailableAt\x12$\n" +
	"\vlease_owner\x18\b \x01(\tH\x00R\n" +
	"leaseOwner\x88\x01\x01\x12\"\n" +
	"\n" +
	"last_error\x18\t \x01(\tH\x01R\tlastError\x88\x01\x01B\x0e\n" +
	"\f_lease_ownerB\r\n" +
	"\v_last_error\"}\n" +
	"\x0eInstanceDetail\x12:\n" +
	"\binstance\x18\x01 \x01(\v2\x1e.com.wiggle.proto.InstanceViewR\binstance\x12/\n" +
	"\x06tokens\x18\x02 \x03(\v2\x17.com.wiggle.proto.TokenR\x06tokens\"\xc1\x01\n" +
	"\x14ListInstancesRequest\x12\x1f\n" +
	"\bworkflow\x18\x01 \x01(\tH\x00R\bworkflow\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\tH\x01R\x06status\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12*\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tH\x02R\rcorrelationId\x88\x01\x01B\v\n" +
	"\t_workflowB\t\n" +
	"\a_statusB\x11\n" +
	"\x0f_correlation_id\"L\n" +
	"\fInstanceList\x12<\n" +
	"\tinstances\x18\x01 \x03(\v2\x1e.com.wiggle.proto.InstanceViewR\tinstances\"4\n" +
	"\x11InstanceIdRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"P\n" +
	"\x15CancelInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"z\n" +
	"\rSignalRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x120\n" +
	"\apayload\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\apayload\"\xab\x01\n" +
	"\x15CreateScheduleRequest\x12\x1a\n" +
	"\bworkflow\x18\x01 \x01(\tR\bworkflow\x12#\n" +
	"\fevery_millis\x18\x02 \x01(\x03H\x00R\veveryMillis\x12\x14\n" +
	"\x04cron\x18\x03 \x01(\tH\x00R\x04cron\x120\n" +
	"\acontext\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\acontextB\t\n" +
	"\acadence\"\xb2\x01\n" +
	"\fScheduleView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bworkflow\x18\x02 \x01(\tR\bworkflow\x12!\n" +
	"\fevery_millis\x18\x03 \x01(\x03R\veveryMillis\x12\x12\n" +
	"\x04cron\x18\x04 \x01(\tR\x04cron\x12 \n" +
	"\fnext_fire_at\x18\x05 \x01(\x03R\n" +
	"nextFireAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"L\n" +
	"\fScheduleList\x12<\n" +
	"\tschedules\x18\x01 \x03(\v2\x1e.com.wiggle.proto.ScheduleViewR\tschedules\"#\n" +
	"\x11ScheduleIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x14CancelInstanceResult\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\tR\tcancelled\"\x98\x01\n" +
	"\vPollRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06queues\x18\x02 \x03(\tR\x06queues\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x05R\x03max\x12!\n" +
	"\flease_millis\x18\x04 \x01(\x03R\vleaseMillis\x12\x1f\n" +
	"\vwait_millis\x18\x05 \x01(\x03R\n" +
	"waitMillis\"\xa0\x04\n" +
	"\x0eTaskActivation\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bworkflow\x18\x03 \x01(\tR\bworkflow\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tstep_name\x18\x06 \x01(\tR\bstepName\x12\x1a\n" +
	"\bactivity\x18\a \x01(\tR\bactivity\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\x12\x18\n" +
	"\aattempt\x18\t \x01(\x05R\aattempt\x12(\n" +
	"\x10lease_expires_at\x18\n" +
	" \x01(\x03R\x0eleaseExpiresAt\x12\x1f\n" +
	"\vlease_owner\x18\v \x01(\tR\n" +
	"leaseOwner\x120\n" +
	"\acontext\x18\f \x01(\v2\x16.google.protobuf.ValueR\acontext\x12%\n" +
	"\x0eexecution_mode\x18\r \x01(\tR\rexecutionMode\x129\n" +
	"\fbase_context\x18\x0e \x01(\v2\x16.google.protobuf.ValueR\vbaseContext\x12\x1d\n" +
	"\n" +
	"item_index\x18\x0f \x01(\x03R\titemIndex\x12 \n" +
	"\fitem_map_key\x18\x10 \x01(\tR\n" +
	"itemMapKey\"p\n" +
	"\bTaskList\x126\n" +
	"\x05tasks\x18\x01 \x03(\v2 .com.wiggle.proto.TaskActivationR\x05tasks\x12,\n" +
	"\x12retry_after_millis\x18\x02 \x01(\x03R\x10retryAfterMillis\"\x8b\x01\n" +
	"\n" +
	"StepResult\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x05merge\x18\x02 \x01(\v2\x16.google.protobuf.ValueH\x00R\x05merge\x12)\n" +
	"\x0fpredicate_value\x18\x03 \x01(\bH\x00R\x0epredicateValueB\t\n" +
	"\aoutcome\"\x97\x01\n" +
	"\x11AdvanceRunRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_owner\x18\x02 \x01(\tR\n" +
	"leaseOwner\x122\n" +
	"\x05steps\x18\x03 \x03(\v2\x1c.com.wiggle.proto.StepResultR\x05steps\x12\x14\n" +
	"\x05final\x18\x04 \x01(\bR\x05final\"\x87\x01\n" +
	"\x10AdvanceRunResult\x12'\n" +
	"\x0finstance_status\x18\x01 \x01(\tR\x0einstanceStatus\x12(\n" +
	"\x10lease_expires_at\x18\x02 \x01(\x03R\x0eleaseExpiresAt\x12 \n" +
	"\fnext_task_id\x18\x03 \x01(\tR\n" +
	"nextTaskId\"}\n" +
	"\x11TaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_owner\x18\x02 \x01(\tR\n" +
	"leaseOwner\x12.\n" +
	"\x06result\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x06result\"\x86\x01\n" +
	"\x12TaskFailureRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_owner\x18\x02 \x01(\tR\n" +
	"leaseOwner\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"q\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vlease_owner\x18\x02 \x01(\tR\n" +
	"leaseOwner\x12#\n" +
	"\rextend_millis\x18\x03 \x01(\x03R\fextendMillis\";\n" +
	"\x0fHeartbeatResult\x12(\n" +
	"\x10lease_expires_at\x18\x01 \x01(\x03R\x0eleaseExpiresAt2\xe7\v\n" +
	"\x12WiggleControlPlane\x12F\n" +
	"\vHealthCheck\x12\x17.com.wiggle.proto.Empty\x1a\x1e.com.wiggle.proto.HealthStatus\x12D\n" +
	"\n" +
	"GetCluster\x12\x17.com.wiggle.proto.Empty\x1a\x1d.com.wiggle.proto.ClusterView\x12I\n" +
	"\rListWorkflows\x12\x17.com.wiggle.proto.Empty\x1a\x1f.com.wiggle.proto.WorkflowNames\x12b\n" +
	"\x10RegisterWorkflow\x12$.com.wiggle.proto.WorkflowDefinition\x1a(.com.wiggle.proto.RegisterWorkflowResult\x12Y\n" +
	"\vGetWorkflow\x12$.com.wiggle.proto.GetWorkflowRequest\x1a$.com.wiggle.proto.WorkflowDefinition\x12^\n" +
	"\rStartInstance\x12&.com.wiggle.proto.StartInstanceRequest\x1a%.com.wiggle.proto.StartInstanceResult\x12W\n" +
	"\rListInstances\x12&.com.wiggle.proto.ListInstancesRequest\x1a\x1e.com.wiggle.proto.InstanceList\x12T\n" +
	"\vGetInstance\x12#.com.wiggle.proto.InstanceIdRequest\x1a .com.wiggle.proto.InstanceDetail\x12a\n" +
	"\x0eCancelInstance\x12'.com.wiggle.proto.CancelInstanceRequest\x1a&.com.wiggle.proto.CancelInstanceResult\x12H\n" +
	"\x0eSignalInstance\x12\x1f.com.wiggle.proto.SignalRequest\x1a\x15.com.wiggle.proto.Ack\x12Y\n" +
	"\x0eCreateSchedule\x12'.com.wiggle.proto.CreateScheduleRequest\x1a\x1e.com.wiggle.proto.ScheduleView\x12H\n" +
	"\rListSchedules\x12\x17.com.wiggle.proto.Empty\x1a\x1e.com.wiggle.proto.ScheduleList\x12L\n" +
	"\x0eDeleteSchedule\x12#.com.wiggle.proto.ScheduleIdRequest\x1a\x15.com.wiggle.proto.Ack\x12F\n" +
	"\tPollTasks\x12\x1d.com.wiggle.proto.PollRequest\x1a\x1a.com.wiggle.proto.TaskList\x12J\n" +
	"\fCompleteTask\x12#.com.wiggle.proto.TaskResultRequest\x1a\x15.com.wiggle.proto.Ack\x12G\n" +
	"\bFailTask\x12$.com.wiggle.proto.TaskFailureRequest\x1a\x15.com.wiggle.proto.Ack\x12V\n" +
	"\rHeartbeatTask\x12\".com.wiggle.proto.HeartbeatRequest\x1a!.com.wiggle.proto.HeartbeatResult\x12U\n" +
	"\n" +
	"AdvanceRun\x12#.com.wiggle.proto.AdvanceRunRequest\x1a\".com.wiggle.proto.AdvanceRunResultBE\n" +
	"\x10com.wiggle.protoP\x01Z/github.com/hadielmougy/wiggle-go/internal/pb;pbb\x06proto3"

var (
	file_wiggle_proto_rawDescOnce sync.Once
	file_wiggle_proto_rawDescData []byte
)

func file_wiggle_proto_rawDescGZIP() []byte {
	file_wiggle_proto_rawDescOnce.Do(func() {
		file_wiggle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wiggle_proto_rawDesc), len(file_wiggle_proto_rawDesc)))
	})
	return file_wiggle_proto_rawDescData
}

var file_wiggle_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_wiggle_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: com.wiggle.proto.Empty
	(*Ack)(nil),                    // 1: com.wiggle.proto.Ack
	(*HealthStatus)(nil),           // 2: com.wiggle.proto.HealthStatus
	(*ClusterMember)(nil),          // 3: com.wiggle.proto.ClusterMember
	(*ClusterView)(nil),            // 4: com.wiggle.proto.ClusterView
	(*WorkflowDefinition)(nil),     // 5: com.wiggle.proto.WorkflowDefinition
	(*WorkflowNames)(nil),          // 6: com.wiggle.proto.WorkflowNames
	(*RegisterWorkflowResult)(nil), // 7: com.wiggle.proto.RegisterWorkflowResult
	(*GetWorkflowRequest)(nil),     // 8: com.wiggle.proto.GetWorkflowRequest
	(*StartInstanceRequest)(nil),   // 9: com.wiggle.proto.StartInstanceRequest
	(*StartInstanceResult)(nil),    // 10: com.wiggle.proto.StartInstanceResult
	(*InstanceView)(nil),           // 11: com.wiggle.proto.InstanceView
	(*Token)(nil),                  // 12: com.wiggle.proto.Token
	(*InstanceDetail)(nil),         // 13: com.wiggle.proto.InstanceDetail
	(*ListInstancesRequest)(nil),   // 14: com.wiggle.proto.ListInstancesRequest
	(*InstanceList)(nil),           // 15: com.wiggle.proto.InstanceList
	(*InstanceIdRequest)(nil),      // 16: com.wiggle.proto.InstanceIdRequest
	(*CancelInstanceRequest)(nil),  // 17: com.wiggle.proto.CancelInstanceRequest
	(*SignalRequest)(nil),          // 18: com.wiggle.proto.SignalRequest
	(*CreateScheduleRequest)(nil),  // 19: com.wiggle.proto.CreateScheduleRequest
	(*ScheduleView)(nil),           // 20: com.wiggle.proto.ScheduleView
	(*ScheduleList)(nil),           // 21: com.wiggle.proto.ScheduleList
	(*ScheduleIdRequest)(nil),      // 22: com.wiggle.proto.ScheduleIdRequest
	(*CancelInstanceResult)(nil),   // 23: com.wiggle.proto.CancelInstanceResult
	(*PollRequest)(nil),            // 24: com.wiggle.proto.PollRequest
	(*TaskActivation)(nil),         // 25: com.wiggle.proto.TaskActivation
	(*TaskList)(nil),               // 26: com.wiggle.proto.TaskList
	(*StepResult)(nil),             // 27: com.wiggle.proto.StepResult
	(*AdvanceRunRequest)(nil),      // 28: com.wiggle.proto.AdvanceRunRequest
	(*AdvanceRunResult)(nil),       // 29: com.wiggle.proto.AdvanceRunResult
	(*TaskResultRequest)(nil),      // 30: com.wiggle.proto.TaskResultRequest
	(*TaskFailureRequest)(nil),     // 31: com.wiggle.proto.TaskFailureRequest
	(*HeartbeatRequest)(nil),       // 32: com.wiggle.proto.HeartbeatRequest
	(*HeartbeatResult)(nil),        // 33: com.wiggle.proto.HeartbeatResult
	(*structpb.Struct)(nil),        // 34: google.protobuf.Struct
	(*structpb.Value)(nil),         // 35: google.protobuf.Value
}
var file_wiggle_proto_depIdxs = []int32{
	3,  // 0: com.wiggle.proto.ClusterView.members:type_name -> com.wiggle.proto.ClusterMember
	34, // 1: com.wiggle.proto.WorkflowDefinition.definition:type_name -> google.protobuf.Struct
	35, // 2: com.wiggle.proto.StartInstanceRequest.context:type_name -> google.protobuf.Value
	35, // 3: com.wiggle.proto.InstanceView.context:type_name -> google.protobuf.Value
	11, // 4: com.wiggle.proto.InstanceDetail.instance:type_name -> com.wiggle.proto.InstanceView
	12, // 5: com.wiggle.proto.InstanceDetail.tokens:type_name -> com.wiggle.proto.Token
	11, // 6: com.wiggle.proto.InstanceList.instances:type_name -> com.wiggle.proto.InstanceView
	35, // 7: com.wiggle.proto.SignalRequest.payload:type_name -> google.protobuf.Value
	35, // 8: com.wiggle.proto.CreateScheduleRequest.context:type_name -> google.protobuf.Value
	20, // 9: com.wiggle.proto.ScheduleList.schedules:type_name -> com.wiggle.proto.ScheduleView
	35, // 10: com.wiggle.proto.TaskActivation.context:type_name -> google.protobuf.Value
	35, // 11: com.wiggle.proto.TaskActivation.base_context:type_name -> google.protobuf.Value
	25, // 12: com.wiggle.proto.TaskList.tasks:type_name -> com.wiggle.proto.TaskActivation
	35, // 13: com.wiggle.proto.StepResult.merge:type_name -> google.protobuf.Value
	27, // 14: com.wiggle.proto.AdvanceRunRequest.steps:type_name -> com.wiggle.proto.StepResult
	35, // 15: com.wiggle.proto.TaskResultRequest.result:type_name -> google.protobuf.Value
	0,  // 16: com.wiggle.proto.WiggleControlPlane.HealthCheck:input_type -> com.wiggle.proto.Empty
	0,  // 17: com.wiggle.proto.WiggleControlPlane.GetCluster:input_type -> com.wiggle.proto.Empty
	0,  // 18: com.wiggle.proto.WiggleControlPlane.ListWorkflows:input_type -> com.wiggle.proto.Empty
	5,  // 19: com.wiggle.proto.WiggleControlPlane.RegisterWorkflow:input_type -> com.wiggle.proto.WorkflowDefinition
	8,  // 20: com.wiggle.proto.WiggleControlPlane.GetWorkflow:input_type -> com.wiggle.proto.GetWorkflowRequest
	9,  // 21: com.wiggle.proto.WiggleControlPlane.StartInstance:input_type -> com.wiggle.proto.StartInstanceRequest
	14, // 22: com.wiggle.proto.WiggleControlPlane.ListInstances:input_type -> com.wiggle.proto.ListInstancesRequest
	16, // 23: com.wiggle.proto.WiggleControlPlane.GetInstance:input_type -> com.wiggle.proto.InstanceIdRequest
	17, // 24: com.wiggle.proto.WiggleControlPlane.CancelInstance:input_type -> com.wiggle.proto.CancelInstanceRequest
	18, // 25: com.wiggle.proto.WiggleControlPlane.SignalInstance:input_type -> com.wiggle.proto.SignalRequest
	19, // 26: com.wiggle.proto.WiggleControlPlane.CreateSchedule:input_type -> com.wiggle.proto.CreateScheduleRequest
	0,  // 27: com.wiggle.proto.WiggleControlPlane.ListSchedules:input_type -> com.wiggle.proto.Empty
	22, // 28: com.wiggle.proto.WiggleControlPlane.DeleteSchedule:input_type -> com.wiggle.proto.ScheduleIdRequest
	24, // 29: com.wiggle.proto.WiggleControlPlane.PollTasks:input_type -> com.wiggle.proto.PollRequest
	30, // 30: com.wiggle.proto.WiggleControlPlane.CompleteTask:input_type -> com.wiggle.proto.TaskResultRequest
	31, // 31: com.wiggle.proto.WiggleControlPlane.FailTask:input_type -> com.wiggle.proto.TaskFailureRequest
	32, // 32: com.wiggle.proto.WiggleControlPlane.HeartbeatTask:input_type -> com.wiggle.proto.HeartbeatRequest
	28, // 33: com.wiggle.proto.WiggleControlPlane.AdvanceRun:input_type -> com.wiggle.proto.AdvanceRunRequest
	2,  // 34: com.wiggle.proto.WiggleControlPlane.HealthCheck:output_type -> com.wiggle.proto.HealthStatus
	4,  // 35: com.wiggle.proto.WiggleControlPlane.GetCluster:output_type -> com.wiggle.proto.ClusterView
	6,  // 36: com.wiggle.proto.WiggleControlPlane.ListWorkflows:output_type -> com.wiggle.proto.WorkflowNames
	7,  // 37: com.wiggle.proto.WiggleControlPlane.RegisterWorkflow:output_type -> com.wiggle.proto.RegisterWorkflowResult
	5,  // 38: com.wiggle.proto.WiggleControlPlane.GetWorkflow:output_type -> com.wiggle.proto.WorkflowDefinition
	10, // 39: com.wiggle.proto.WiggleControlPlane.StartInstance:output_type -> com.wiggle.proto.StartInstanceResult
	15, // 40: com.wiggle.proto.WiggleControlPlane.ListInstances:output_type -> com.wiggle.proto.InstanceList
	13, // 41: com.wiggle.proto.WiggleControlPlane.GetInstance:output_type -> com.wiggle.proto.InstanceDetail
	23, // 42: com.wiggle.proto.WiggleControlPlane.CancelInstance:output_type -> com.wiggle.proto.CancelInstanceResult
	1,  // 43: com.wiggle.proto.WiggleControlPlane.SignalInstance:output_type -> com.wiggle.proto.Ack
	20, // 44: com.wiggle.proto.WiggleControlPlane.CreateSchedule:output_type -> com.wiggle.proto.ScheduleView
	21, // 45: com.wiggle.proto.WiggleControlPlane.ListSchedules:output_type -> com.wiggle.proto.ScheduleList
	1,  // 46: com.wiggle.proto.WiggleControlPlane.DeleteSchedule:output_type -> com.wiggle.proto.Ack
	26, // 47: com.wiggle.proto.WiggleControlPlane.PollTasks:output_type -> com.wiggle.proto.TaskList
	1,  // 48: com.wiggle.proto.WiggleControlPlane.CompleteTask:output_type -> com.wiggle.proto.Ack
	1,  // 49: com.wiggle.proto.WiggleControlPlane.FailTask:output_type -> com.wiggle.proto.Ack
	33, // 50: com.wiggle.proto.WiggleControlPlane.HeartbeatTask:output_type -> com.wiggle.proto.HeartbeatResult
	29, // 51: com.wiggle.proto.WiggleControlPlane.AdvanceRun:output_type -> com.wiggle.proto.AdvanceRunResult
	34, // [34:52] is the sub-list for method output_type
	16, // [16:34] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_wiggle_proto_init() }
func file_wiggle_proto_init() {
	if File_wiggle_proto != nil {
		return
	}
	file_wiggle_proto_msgTypes[9].OneofWrappers = []any{}
	file_wiggle_proto_msgTypes[11].OneofWrappers = []any{}
	file_wiggle_proto_msgTypes[12].OneofWrappers = []any{}
	file_wiggle_proto_msgTypes[14].OneofWrappers = []any{}
	file_wiggle_proto_msgTypes[19].OneofWrappers = []any{
		(*CreateScheduleRequest_EveryMillis)(nil),
		(*CreateScheduleRequest_Cron)(nil),
	}
	file_wiggle_proto_msgTypes[27].OneofWrappers = []any{
		(*StepResult_Merge)(nil),
		(*StepResult_PredicateValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wiggle_proto_rawDesc), len(file_wiggle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wiggle_proto_goTypes,
		DependencyIndexes: file_wiggle_proto_depIdxs,
		MessageInfos:      file_wiggle_proto_msgTypes,
	}.Build()
	File_wiggle_proto = out.File
	file_wiggle_proto_goTypes = nil
	file_wiggle_proto_depIdxs = nil
}
