// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: wiggle.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WiggleControlPlane_HealthCheck_FullMethodName      = "/dev.wiggle.proto.WiggleControlPlane/HealthCheck"
	WiggleControlPlane_GetCluster_FullMethodName       = "/dev.wiggle.proto.WiggleControlPlane/GetCluster"
	WiggleControlPlane_ListWorkflows_FullMethodName    = "/dev.wiggle.proto.WiggleControlPlane/ListWorkflows"
	WiggleControlPlane_RegisterWorkflow_FullMethodName = "/dev.wiggle.proto.WiggleControlPlane/RegisterWorkflow"
	WiggleControlPlane_GetWorkflow_FullMethodName      = "/dev.wiggle.proto.WiggleControlPlane/GetWorkflow"
	WiggleControlPlane_StartInstance_FullMethodName    = "/dev.wiggle.proto.WiggleControlPlane/StartInstance"
	WiggleControlPlane_ListInstances_FullMethodName    = "/dev.wiggle.proto.WiggleControlPlane/ListInstances"
	WiggleControlPlane_GetInstance_FullMethodName      = "/dev.wiggle.proto.WiggleControlPlane/GetInstance"
	WiggleControlPlane_CancelInstance_FullMethodName   = "/dev.wiggle.proto.WiggleControlPlane/CancelInstance"
	WiggleControlPlane_SignalInstance_FullMethodName   = "/dev.wiggle.proto.WiggleControlPlane/SignalInstance"
	WiggleControlPlane_CreateSchedule_FullMethodName   = "/dev.wiggle.proto.WiggleControlPlane/CreateSchedule"
	WiggleControlPlane_ListSchedules_FullMethodName    = "/dev.wiggle.proto.WiggleControlPlane/ListSchedules"
	WiggleControlPlane_DeleteSchedule_FullMethodName   = "/dev.wiggle.proto.WiggleControlPlane/DeleteSchedule"
	WiggleControlPlane_PollTasks_FullMethodName        = "/dev.wiggle.proto.WiggleControlPlane/PollTasks"
	WiggleControlPlane_CompleteTask_FullMethodName     = "/dev.wiggle.proto.WiggleControlPlane/CompleteTask"
	WiggleControlPlane_FailTask_FullMethodName         = "/dev.wiggle.proto.WiggleControlPlane/FailTask"
	WiggleControlPlane_HeartbeatTask_FullMethodName    = "/dev.wiggle.proto.WiggleControlPlane/HeartbeatTask"
	WiggleControlPlane_AdvanceRun_FullMethodName       = "/dev.wiggle.proto.WiggleControlPlane/AdvanceRun"
)

// WiggleControlPlaneClient is the client API for WiggleControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The control-plane API. Workers pull work from here; nothing is ever pushed to them,
// so workers need no inbound connectivity and can scale independently of the servers.
type WiggleControlPlaneClient interface {
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error)
	GetCluster(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ClusterView, error)
	ListWorkflows(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkflowNames, error)
	RegisterWorkflow(ctx context.Context, in *WorkflowDefinition, opts ...grpc.CallOption) (*RegisterWorkflowResult, error)
	GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*WorkflowDefinition, error)
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResult, error)
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*InstanceList, error)
	GetInstance(ctx context.Context, in *InstanceIdRequest, opts ...grpc.CallOption) (*InstanceDetail, error)
	CancelInstance(ctx context.Context, in *CancelInstanceRequest, opts ...grpc.CallOption) (*CancelInstanceResult, error)
	// Delivers a named signal to a running instance; the payload merges into its context.
	SignalInstance(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*Ack, error)
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*ScheduleView, error)
	ListSchedules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScheduleList, error)
	DeleteSchedule(ctx context.Context, in *ScheduleIdRequest, opts ...grpc.CallOption) (*Ack, error)
	PollTasks(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*TaskList, error)
	CompleteTask(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*Ack, error)
	FailTask(ctx context.Context, in *TaskFailureRequest, opts ...grpc.CallOption) (*Ack, error)
	HeartbeatTask(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResult, error)
	// Applies an ordered run of locally-executed steps atomically, keeps the lease, and reports
	// whether the worker should keep going (LOCAL_SYNC / LOCAL_ASYNC execution).
	AdvanceRun(ctx context.Context, in *AdvanceRunRequest, opts ...grpc.CallOption) (*AdvanceRunResult, error)
}

type wiggleControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewWiggleControlPlaneClient(cc grpc.ClientConnInterface) WiggleControlPlaneClient {
	return &wiggleControlPlaneClient{cc}
}

func (c *wiggleControlPlaneClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatus)
	err := c.cc.Invoke(ctx, WiggleControlPlane_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) GetCluster(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ClusterView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterView)
	err := c.cc.Invoke(ctx, WiggleControlPlane_GetCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) ListWorkflows(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkflowNames, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowNames)
	err := c.cc.Invoke(ctx, WiggleControlPlane_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) RegisterWorkflow(ctx context.Context, in *WorkflowDefinition, opts ...grpc.CallOption) (*RegisterWorkflowResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkflowResult)
	err := c.cc.Invoke(ctx, WiggleControlPlane_RegisterWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*WorkflowDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowDefinition)
	err := c.cc.Invoke(ctx, WiggleControlPlane_GetWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInstanceResult)
	err := c.cc.Invoke(ctx, WiggleControlPlane_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*InstanceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceList)
	err := c.cc.Invoke(ctx, WiggleControlPlane_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) GetInstance(ctx context.Context, in *InstanceIdRequest, opts ...grpc.CallOption) (*InstanceDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceDetail)
	err := c.cc.Invoke(ctx, WiggleControlPlane_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) CancelInstance(ctx context.Context, in *CancelInstanceRequest, opts ...grpc.CallOption) (*CancelInstanceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelInstanceResult)
	err := c.cc.Invoke(ctx, WiggleControlPlane_CancelInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) SignalInstance(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WiggleControlPlane_SignalInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*ScheduleView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleView)
	err := c.cc.Invoke(ctx, WiggleControlPlane_CreateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) ListSchedules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ScheduleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleList)
	err := c.cc.Invoke(ctx, WiggleControlPlane_ListSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) DeleteSchedule(ctx context.Context, in *ScheduleIdRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WiggleControlPlane_DeleteSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) PollTasks(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*TaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskList)
	err := c.cc.Invoke(ctx, WiggleControlPlane_PollTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) CompleteTask(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WiggleControlPlane_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) FailTask(ctx context.Context, in *TaskFailureRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WiggleControlPlane_FailTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) HeartbeatTask(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResult)
	err := c.cc.Invoke(ctx, WiggleControlPlane_HeartbeatTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wiggleControlPlaneClient) AdvanceRun(ctx context.Context, in *AdvanceRunRequest, opts ...grpc.CallOption) (*AdvanceRunResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvanceRunResult)
	err := c.cc.Invoke(ctx, WiggleControlPlane_AdvanceRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WiggleControlPlaneServer is the server API for WiggleControlPlane service.
// All implementations must embed UnimplementedWiggleControlPlaneServer
// for forward compatibility.
//
// The control-plane API. Workers pull work from here; nothing is ever pushed to them,
// so workers need no inbound connectivity and can scale independently of the servers.
type WiggleControlPlaneServer interface {
	HealthCheck(context.Context, *Empty) (*HealthStatus, error)
	GetCluster(context.Context, *Empty) (*ClusterView, error)
	ListWorkflows(context.Context, *Empty) (*WorkflowNames, error)
	RegisterWorkflow(context.Context, *WorkflowDefinition) (*RegisterWorkflowResult, error)
	GetWorkflow(context.Context, *GetWorkflowRequest) (*WorkflowDefinition, error)
	StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResult, error)
	ListInstances(context.Context, *ListInstancesRequest) (*InstanceList, error)
	GetInstance(context.Context, *InstanceIdRequest) (*InstanceDetail, error)
	CancelInstance(context.Context, *CancelInstanceRequest) (*CancelInstanceResult, error)
	// Delivers a named signal to a running instance; the payload merges into its context.
	SignalInstance(context.Context, *SignalRequest) (*Ack, error)
	CreateSchedule(context.Context, *CreateScheduleRequest) (*ScheduleView, error)
	ListSchedules(context.Context, *Empty) (*ScheduleList, error)
	DeleteSchedule(context.Context, *ScheduleIdRequest) (*Ack, error)
	PollTasks(context.Context, *PollRequest) (*TaskList, error)
	CompleteTask(context.Context, *TaskResultRequest) (*Ack, error)
	FailTask(context.Context, *TaskFailureRequest) (*Ack, error)
	HeartbeatTask(context.Context, *HeartbeatRequest) (*HeartbeatResult, error)
	// Applies an ordered run of locally-executed steps atomically, keeps the lease, and reports
	// whether the worker should keep going (LOCAL_SYNC / LOCAL_ASYNC execution).
	AdvanceRun(context.Context, *AdvanceRunRequest) (*AdvanceRunResult, error)
	mustEmbedUnimplementedWiggleControlPlaneServer()
}

// UnimplementedWiggleControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWiggleControlPlaneServer struct{}

func (UnimplementedWiggleControlPlaneServer) HealthCheck(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWiggleControlPlaneServer) GetCluster(context.Context, *Empty) (*ClusterView, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCluster not implemented")
}
func (UnimplementedWiggleControlPlaneServer) ListWorkflows(context.Context, *Empty) (*WorkflowNames, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedWiggleControlPlaneServer) RegisterWorkflow(context.Context, *WorkflowDefinition) (*RegisterWorkflowResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorkflow not implemented")
}
func (UnimplementedWiggleControlPlaneServer) GetWorkflow(context.Context, *GetWorkflowRequest) (*WorkflowDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflow not implemented")
}
func (UnimplementedWiggleControlPlaneServer) StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResult, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedWiggleControlPlaneServer) ListInstances(context.Context, *ListInstancesRequest) (*InstanceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedWiggleControlPlaneServer) GetInstance(context.Context, *InstanceIdRequest) (*InstanceDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedWiggleControlPlaneServer) CancelInstance(context.Context, *CancelInstanceRequest) (*CancelInstanceResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInstance not implemented")
}
func (UnimplementedWiggleControlPlaneServer) SignalInstance(context.Context, *SignalRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalInstance not implemented")
}
func (UnimplementedWiggleControlPlaneServer) CreateSchedule(context.Context, *CreateScheduleRequest) (*ScheduleView, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedWiggleControlPlaneServer) ListSchedules(context.Context, *Empty) (*ScheduleList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchedules not implemented")
}
func (UnimplementedWiggleControlPlaneServer) DeleteSchedule(context.Context, *ScheduleIdRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (UnimplementedWiggleControlPlaneServer) PollTasks(context.Context, *PollRequest) (*TaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method PollTasks not implemented")
}
func (UnimplementedWiggleControlPlaneServer) CompleteTask(context.Context, *TaskResultRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedWiggleControlPlaneServer) FailTask(context.Context, *TaskFailureRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method FailTask not implemented")
}
func (UnimplementedWiggleControlPlaneServer) HeartbeatTask(context.Context, *HeartbeatRequest) (*HeartbeatResult, error) {
	return nil, status.Error(codes.Unimplemented, "method HeartbeatTask not implemented")
}
func (UnimplementedWiggleControlPlaneServer) AdvanceRun(context.Context, *AdvanceRunRequest) (*AdvanceRunResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvanceRun not implemented")
}
func (UnimplementedWiggleControlPlaneServer) mustEmbedUnimplementedWiggleControlPlaneServer() {}
func (UnimplementedWiggleControlPlaneServer) testEmbeddedByValue()                            {}

// UnsafeWiggleControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WiggleControlPlaneServer will
// result in compilation errors.
type UnsafeWiggleControlPlaneServer interface {
	mustEmbedUnimplementedWiggleControlPlaneServer()
}

func RegisterWiggleControlPlaneServer(s grpc.ServiceRegistrar, srv WiggleControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedWiggleControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WiggleControlPlane_ServiceDesc, srv)
}

func _WiggleControlPlane_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_GetCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).GetCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_GetCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).GetCluster(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).ListWorkflows(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_RegisterWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowDefinition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).RegisterWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_RegisterWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).RegisterWorkflow(ctx, req.(*WorkflowDefinition))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_GetWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).GetWorkflow(ctx, req.(*GetWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).StartInstance(ctx, req.(*StartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).GetInstance(ctx, req.(*InstanceIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_CancelInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).CancelInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_CancelInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).CancelInstance(ctx, req.(*CancelInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_SignalInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).SignalInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_SignalInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).SignalInstance(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_CreateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_ListSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).ListSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_ListSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).ListSchedules(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_DeleteSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).DeleteSchedule(ctx, req.(*ScheduleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_PollTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).PollTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_PollTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).PollTasks(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).CompleteTask(ctx, req.(*TaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_FailTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).FailTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_FailTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).FailTask(ctx, req.(*TaskFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_HeartbeatTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).HeartbeatTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_HeartbeatTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).HeartbeatTask(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WiggleControlPlane_AdvanceRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvanceRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WiggleControlPlaneServer).AdvanceRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WiggleControlPlane_AdvanceRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WiggleControlPlaneServer).AdvanceRun(ctx, req.(*AdvanceRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WiggleControlPlane_ServiceDesc is the grpc.ServiceDesc for WiggleControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WiggleControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dev.wiggle.proto.WiggleControlPlane",
	HandlerType: (*WiggleControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _WiggleControlPlane_HealthCheck_Handler,
		},
		{
			MethodName: "GetCluster",
			Handler:    _WiggleControlPlane_GetCluster_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _WiggleControlPlane_ListWorkflows_Handler,
		},
		{
			MethodName: "RegisterWorkflow",
			Handler:    _WiggleControlPlane_RegisterWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _WiggleControlPlane_GetWorkflow_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _WiggleControlPlane_StartInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _WiggleControlPlane_ListInstances_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _WiggleControlPlane_GetInstance_Handler,
		},
		{
			MethodName: "CancelInstance",
			Handler:    _WiggleControlPlane_CancelInstance_Handler,
		},
		{
			MethodName: "SignalInstance",
			Handler:    _WiggleControlPlane_SignalInstance_Handler,
		},
		{
			MethodName: "CreateSchedule",
			Handler:    _WiggleControlPlane_CreateSchedule_Handler,
		},
		{
			MethodName: "ListSchedules",
			Handler:    _WiggleControlPlane_ListSchedules_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _WiggleControlPlane_DeleteSchedule_Handler,
		},
		{
			MethodName: "PollTasks",
			Handler:    _WiggleControlPlane_PollTasks_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _WiggleControlPlane_CompleteTask_Handler,
		},
		{
			MethodName: "FailTask",
			Handler:    _WiggleControlPlane_FailTask_Handler,
		},
		{
			MethodName: "HeartbeatTask",
			Handler:    _WiggleControlPlane_HeartbeatTask_Handler,
		},
		{
			MethodName: "AdvanceRun",
			Handler:    _WiggleControlPlane_AdvanceRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wiggle.proto",
}
